#+Title: Of Wilds and Wastes TTRPG

* Introduction

** World of Wilds and Wastes

The world of Of Wilds and Wastes began with the titans. The colossal beings used might and magic to shear the plains flat, heat the core of the planet, and gift the world with water and sun. Today, their fossilized remains are strewn about the world in hidden groves. Nobody knows how they came to die, but legend says that they gave up their power willingly, to share their earthen canvas with the rest of life's creatures.

Without the chaos of the titan's ongoing construction, the creatures of the world were allowed to grow and evolve. With enough time, the lands became overgrown with all manner of beast. Intelligence alone was not enough to live at the top of the food chain, so lowly humans were relegated to hiding and building what defenses they could, praying that their independent settlements not fall victim to ruin.

But the world is beginning to change once again. Humans are uncovering the magic that the titans left behind. With this newfound power, they are striking out, exploring the world, and trading with others for the first time. It is in this setting that Of Wilds and Wastes takes place. There is high demand for those who can defend against the wilds. The best adventurers of the world are renowned and exalted, but not many of them are very wrinkled...

** What is needed to play

Of Wilds and Wastes is meant to be played with two or more players. The sweet spot is 3 to 5 players and another player be the Game Master, abbreviated GM from here on out.

Each player requires one full set of RPG dice: a four sided die (d4), a six sided die (d6), a ten sided die (d10), a twelve sided die (d12), a twenty sided die (d20), and a tens marked ten sided die (used with the d10 to make a d100).

It is recommended to have two sets per player so that multi-dice rolls can occur at once.

Any die with a zero side is used as the max value for the die. For example, the zero on a d10 has a value of 10.

** Creating a Character

Use the following checklist to create a new character.

- Download a new character sheet
- Decide on a [[* Player Classes][player class]]
  - Fill in the class name
  - Fill in the starting stats assigned to your class
- Decide on a [[* Systems of Magic][magic system]] compatible with your player class
  - Fill in the magic system name
  - Fill in your starting spell choices
- Decide on a starting skill
  - Fill in your starting skill
- Fill in your character name

* Combat

In combat, players and enemies take turns performing actions. A turn is broken up into one major action, one minor action, and as many as needed free actions. One is always free to use a minor action in place of a major action.

** Default Major Actions

*** Weapon Attack

Characters make an attack against an enemy using an equipped weapon. An unarmed attack can be made for 1 damage if no weapons are equipped.

*** Spell Cast

Characters who are learned in a [[* Systems of Magic][school of magic]] that provides spells marked as a major action can cast them as such.

** Default Minor Actions

*** Movement

Characters move up to their [[* Movement Speed][movement speed]].

*** Swapping Held Items

Characters put away, replace, or take out items that can be used when held.

*** Reloading

Characters load ammunition into a ranged weapon, a bow for example.

** Conditions

*** Incapacitated

When a player drops below 0 HP, they become incapacitated. They are unable to take major or minor actions or regain HP normally.

Upon entering the state, they make a power [[* Ability Check][ability check]] (12). On a successful check, the character returns to 0 HP, and the effect ends at the end of the current fight. On a failed check, the character stays incapacitated until [[* Recovery][recovery]], and the character becomes afflicted by a [[* Grevious Wound][grevious wound]].

The condition can also be ended by a spell or item that provides the revive affect, returning the character to 1 HP and ending the effect, even during battle.

Every time a character is attacked while incapacitated, they suffer another [[* Grevious Wound][grevious wound]]. Some foes may ignore downed combatants, but not all are so merciful.

*** Death

Death is the end of your playable character. They have succumbed to their injuries and pass on to the final rest.

This is a good chance to say some final words to your comrades.

** Grievous Wound

When a character sustains critical injury, they become afflicted by a grievous wound. Roll a d6 to determine your characters grievous wound. This wounds cannot be removed by normal healing. If the same grievous wound is rolled two times in a row, then the character suffers [[* Death][death]].

*** (1) Head Trauma

The character is unable to remember people and motivations from their past. They must invent a new false backstory or find a new purpose.

*** (2) Missing Arm

Damage to one arm becomes too severe to save. Your character is no longer able to wield two handed equipment and can only wield one one handed equipment.

*** (3) Severed Magical Connection

Injuries the body sever the connection a player has with their school of magic. Their [[* Magic Power (MP)][MP]] is halved.

*** (4) Gnarly Scars

The many wounds gained over time have accumulated and worn down the player. Their maximum [[* Health Points (HP)][HP]] is halved.

*** (5) Unset Fracture

Bone injuries have left the player with a worn gait. Their base [[* Movement Speed][movement speed]] is halved.

*** (6) Death

The character experiences [[* Death][death]].

** Recovering

Recovering is the process of regaining HP and MP. Certain classes regain additional resources while recovering.

*** Respite

A respite is the only recovery that can occur while out adventuring. A respite requires an uninterrupted rest of at least 4 hours. Spending 8 or more hours resting does not increase the resources gained, and a respite can only occur once a day.

After a respite, each player rolls a d6 up to their character level number of times. The players choose whether to add the value on the die rolled to their [[*** Health Points (HP)][HP]] or [[*** Magic Power (MP)][MP]].

Once character level number of respite dice have been rolled, no more can be rolled until a full recovery has occurred.

Respite can be modified by certain [[* Player Classes][classes]] and [[* Systems of Magic][magic systems]].

*** Full Recovery

A full recovery restores all of a character's [[* Health Points (HP)][HP]] and [[* Magic Power (MP)][MP]], but can only occur in [[* Towns][town]] over the period of a week. A full recovery will reset the number of respite dice rolled back to zero.

* Roleplaying

** Skills

Skills are trades that can be learned while in [[* Towns][town]] in order to augment a characters abilities.

*** Alchemy

*** Bow Training

*** Horseback Riding

*** Lockpicking

*** Shield Training

*** Smithing

** Ability Check

Ability checks are a way to use dice in combination with player stats to resolve an outcome.

The DM will ask for an ability check of a player for a particular [[** The Main Stats][main stat]]. It's the players job to roll a d12 and add their stat to the roll. It will then be up to the DM to resolve outcome.

** Dialog

Speaking with Non-Player Characters (NPCs) is a common part of adventuring. Players may wish to elicit information from a knowledgeable town resident, haggle on the price of a rare artifact, or convince an animal that they are friendly.

When players are expecting a result out of their conversation, it's the job of the DM to recognize this and ask for an [[* Ability Check][ability check]]. Players have many ways to be convincing, and the strength of their argument can have a great affect on the difficulty of the ability check.

Dialog is also one of the best ways to show off your character's personality!

* Character Stats

** Character Level

The level of your character is a measure of how skilled they are at their craft. This skill is manifested in additional stats, features, and magical ability.

Character level starts at 1 and goes up to 16. In order to level up, characters need to both gain experience out adventuring and spend time and money in [[* Towns][town]]. Your DM will let you know when you have gained enough experience to advance in level, but it is up to you to choose when to spend the time and money to learn the next level during [[** Town Actions][your town actions]].

At the 6th level, a study under a master is required. Masters are not uncommon, but are not found in every town. At the 11th level, a study under a grandmaster is required. Although most grandmasters are well known in story and legend, not all of them can be easy to find. In order to attain the 16th level, one has to advance their field beyond it's current limits. Work with your DM to discuss your plan for this, as such things do not come with a one size fits all price tag.

Use the following requirements chart to see what it takes to make it to level up. The monetary price to level up does not include [[** Living Expenses][living expenses]].

| Level | Location          | Time     | Monetary Cost | Rank           |
|-------+-------------------+----------+---------------+----------------|
|     1 | N/A               | N/A      | N/A           | Apprentice     |
|     2 | Adventure Hall    | 1 month  | 100 Shells    | Apprentice II  |
|     3 | Adventure Hall    | 1 month  | 200 Shells    | Apprentice III |
|     4 | Adventure Hall    | 1 month  | 300 Shells    | Apprentice IV  |
|     5 | Adventure Hall    | 1 month  | 400 Shells    | Apprentice V   |
|     6 | Master Study      | 6 months | 1000 Shells   | Journeyman     |
|     7 | Adventure Hall    | 2 months | 1200 Shells   | Journeyman II  |
|     8 | Adventure Hall    | 2 months | 1400 Shells   | Journeyman III |
|     9 | Adventure Hall    | 2 months | 1600 Shells   | Journeyman IV  |
|    10 | Adventure Hall    | 2 months | 1800 Shells   | Journeyman V   |
|    11 | Grandmaster Study | 1 year   | 3000 Shells   | Master         |
|    12 | Adventure Hall    | 3 months | 3500 Shells   | Master II      |
|    13 | Adventure Hall    | 3 months | 4000 Shells   | Master III     |
|    14 | Adventure Hall    | 3 months | 4500 Shells   | Master IV      |
|    15 | Adventure Hall    | 3 months | 5000 Shells   | Master V       |
|    16 | ?                 | ?        | ?             | Grandmaster    |

** The Main Stats

Main stats are the primary stats in the game. Actions with an uncertain outcome are almost always modified by one of these through [[** Ability Check][ability checks]].

These stats range from 1 to 16. When stats are upgraded, the effects of stats are always retroactive. Stats are broken up into the following categories:

*** Power

/Power is used to express physical strength. Cleave, crush, and grapple your way through enemies./

Effects:

- Extra HP per level: Power / 4

*** Reflex

/Reflex measures your speed and reaction. Evade dangers and act before others. A high reflex shoots first./

Effects:

- Combat order: Higher reflex acts first

*** Focus

/Focus allows you to concentrate and understand complex concepts. Perceive the dangers around you and outwit opponents./

Effects:

- Extra MP per level: Focus / 4

*** Presence

/A high presence signifies awareness of the world around you. Anticipate the actions of others and make them pay for their predictability./

Effects:

- Critical strike chance: D20 roll <= Presence

** Auxiliary Stats

*** Health Points (HP)

Health points tracks the life of your character. The closer to 0, the closer your character is to [[* Death][death]]. Characters gain extra health at every level based on their [[* Player Classes][class]].

*** Magic Power (MP)

Magic power tracks the amount of magic that a character can perform. Characters gain extra health at every level based on their [[* Player Classes][class]].

*** Movement Speed

Movement speed is a measure how fast your character is. In [[* Combat][combat]], your character is allowed to move up to their movement speed in squares every round.

When moving diagonal, treat the first diagonal move as one square of movement, the second diagonal move as two squares of movement, then one, then two, etc.

* Towns

Towns provide a safe haven between adventures, a place to rest weary bones, and prepare for what's next.

** Living Expenses

Every month of time spent in town incurs living expenses. The price of these expenses depends upon your desired station. It may be tempting to choose meager living expenses, but know that you station effects how others perceive you. The rarest [[** Artifacts][artifacts]] and most lucrative jobs often go to those of high station. The prices for living expenses are shown in the following table.

| Station | Monthly Expenses |
|---------+------------------|
| Meager  | 50 Shells        |
| Frugal  | 100 Shells       |
| Average | 200 Shells       |
| High    | 500 Shells       |
| Royal   | 1000 Shells      |

** Town Actions

You may be returning to town just for the sake of a [[*** Full Recovery][full recovery]], but why not take advantage of what the town has to offer? Time spent in town is devoted to town actions. Town actions occur on the order of months, and each member of the party need not take the same town action at the same time.

*** Mentorship

*** Philanthropy

*** Real Estate

*** Research

*** Shopping

*** Skill Studying

* Player Classes

** Tactician

/"Victory requires no hope, it is assured."/

Tacticians are able to survey a battlefield with ease. They are able to command allies, increasing their battle effectiveness, and have insight into enemies traits.

HP per Level: 8
MP per Level: 8

One standard magic system

** Mercenary

/"Imagine bringing a pen to battle."/

Mercenaries are masters of combat and weaponry, able to wield the rarest weapons and strongest armors. Cleaving and rending is the way of the Mercenary.

HP per Level: 10
MP per Level: 6

One standard magic system

** Assassin

/"How easy one slips into the long dark."/

Assassins are skilled dealing damage through the use of well placed attacks and devious weapon modifications. Few can stand before an Assassin and live to tell the tale.

HP per Level: 8
MP per Level: 8

One standard magic system

** Scholar

/"To seek no knowledge is to squander life and live as does the commonest weed."/

Scholars are those who seek to understand the titan's influence on the world. The knowledge is only a mimicry, but even a fraction of that power is enough to demand respect.

HP per Level: 6
MP per Level: 10

One advanced magic system

** Bereft

/"Passed by without so much as a glance."/

The Bereft are those without any advantage. Unlikely adventurers, but it is not for fate to say who are the greats.

HP per Level: 6
MP per Level: 0

No magic.

* Systems of Magic

The power of the titans left its mark on the world. The study of these marks led to the beginning of the practice of magic. Independently, the studies led in different paths that lead to the groups of magic that are currently known.

Each group requires a lifetime of practice and a focus to the craft. Even then, some advanced magics are only able to be learned by those who give their complete energy to the study. These are known as advanced magics, while the easier, but still rare, magics are called the standard magics.

** Standard Magics

*** Runecast

The Runecast are warriors that pursue the study of an ancient written language. By etching these runic symbols into their weapons and armor, they are able to bind the power of magic to physical objects, and augment their combat ability.

Carving runes into your weapons and armor reserves [[* Magic Power (MP)][MP]]. The passive effects of these runes are always present. Runecast are only able to modify their own equipment.

The number of runes that can be equipped at a time is shown in the following table.

| Level | # of Runes |
|-------+------------|
|     1 | 1          |
|     2 | 2          |
|     3 | 2          |
|     4 | 3          |
|     5 | 3          |
|     6 | 4          |
|     7 | 4          |
|     8 | 5          |
|     9 | 5          |
|    10 | 6          |
|    11 | 7          |
|    12 | 7          |
|    13 | 8          |
|    14 | 8          |
|    15 | 9          |
|    16 | 11         |

*** Spirit Caller

Spirit Callers hold a spiritual bond with their ancestors. In death, the spirits of the departed are able to impart their favors upon the physical world.

These effects are limited by the number of favors available and can be activated a number of times per combat shown in the following table.

| Level | # Casts Per Combat | # Favors Available |
|-------+--------------------+--------------------|
|     1 |                  1 |                  1 |
|     2 |                  2 |                  2 |
|     3 |                  2 |                  2 |
|     4 |                  2 |                  3 |
|     5 |                  2 |                  3 |
|     6 |                  3 |                  5 |
|     7 |                  3 |                  5 |
|     8 |                  3 |                  6 |
|     9 |                  3 |                  6 |
|    10 |                  3 |                  7 |
|    11 |                  4 |                  9 |
|    12 |                  4 |                  9 |
|    13 |                  4 |                 10 |
|    14 |                  4 |                 10 |
|    15 |                  4 |                 11 |
|    16 |                  5 |                 13 |

*** Harvester

Harvesters utilize the remains of the fallen, twisting them to their own purposes. They collect soul pieces from those that die during combat, which are manipulated to their end through the use of spells called extractions.

The number of known extractions and maximum number of should pieces that can be held at the same time are shown in the following table.

| Level | # Extractions Known | Max Soul Pieces |
|-------+---------------------+-----------------|
|     1 |                   1 |               3 |
|     2 |                   2 |               4 |
|     3 |                   2 |               4 |
|     4 |                   3 |               5 |
|     5 |                   3 |               5 |
|     6 |                   5 |               7 |
|     7 |                   5 |               7 |
|     8 |                   6 |               8 |
|     9 |                   6 |               8 |
|    10 |                   7 |               9 |
|    11 |                   9 |              11 |
|    12 |                   9 |              11 |
|    13 |                  10 |              12 |
|    14 |                  10 |              12 |
|    15 |                  11 |              13 |
|    16 |                  13 |              15 |

*** Beastheart

Beasthearts are those who have formed a magical bond with a beast companion. Time spent in the wilds has formed a shared consciousness with their 


** Advanced Magics

*** Ancient Whisperer

The Ancient Whisperers have studied the lost spoken language of the titans. Through great mental exertion, they can recall incantations the forgotten language, shaping the world as the titans once did.

The number of known incantations are shown in the following table.

| Level | # Incantations Known |
|-------+----------------------|
|     1 |                    1 |
|     2 |                    2 |
|     3 |                    3 |
|     4 |                    4 |
|     5 |                    5 |
|     6 |                    6 |
|     7 |                    7 |
|     8 |                    8 |
|     9 |                    9 |
|    10 |                   10 |
|    11 |                   11 |
|    12 |                   12 |
|    13 |                   13 |
|    14 |                   14 |
|    15 |                   15 |
|    16 |                   16 |

*** Elementalist

Elementalists draw from the latent magic left behind from the construction of the world.


Elemental spells, called sourceries, can be devastatingly powerful, but rely on the setup and maintenance of elemental catalysts. Elementalists learn major and minor sourceries that can be used as major and minor actions. TODO Add element section

| Level | # Major Sourceries Known | # Minor Sourceries Known |
|-------+--------------------------+--------------------------|
|     1 |                        1 |                        1 |
|     2 |                        2 |                        2 |
|     3 |                        2 |                        2 |
|     4 |                        3 |                        2 |
|     5 |                        3 |                        2 |
|     6 |                        5 |                        3 |
|     7 |                        5 |                        3 |
|     8 |                        6 |                        3 |
|     9 |                        6 |                        3 |
|    10 |                        7 |                        3 |
|    11 |                        9 |                        4 |
|    12 |                        9 |                        4 |
|    13 |                       10 |                        4 |
|    14 |                       10 |                        4 |
|    15 |                       11 |                        4 |
|    16 |                       13 |                        5 |

* Equipment

** Adventuring Equipment

** Artifacts

** Currency

TODO
