#+Title: Titan Mage Player's Handbook
#+HTML_LINK_HOME: dummy value
#+OPTIONS: toc:t toc:2

* Introduction

** The World of Titan Mage

The world of Titan Mage began with the titans. The colossal beings used might and magic to shear the plains flat, heat the core of the planet, and gift the world with water and sun. Today, their fossilized remains are strewn about the world in hidden groves. Nobody knows how they came to die, but legend says that they gave up their power willingly, to share their earthen canvas with the rest of life's creatures.

Without the chaos of the titan's ongoing construction, the creatures of the world were allowed to grow and evolve. With enough time, the lands became overgrown with all manner of beast. Intelligence alone was not enough to live at the top of the food chain, so lowly humans were relegated to hiding and building what defenses they could, praying that their independent settlements not fall victim to ruin.

But the world is beginning to change once again. Humans are uncovering the magic that the titans left behind. With this newfound power, they are striking out, exploring the world, and trading with others for the first time. It is in this setting that Titan Mage takes place. There is high demand for those who can defend against the wilds. The best adventurers of the world are renowned and exalted, but not many of them are very wrinkled...

** What is Needed to Play

Titan Mage is meant to be played with two or more players. The sweet spot is 3 to 5 players and another player be the Game Master, abbreviated GM from here on out.

Each player requires one full set of RPG dice: a four sided die (d4), a six sided die (d6), a ten sided die (d10), a twelve sided die (d12), a twenty sided die (d20), and a tens marked ten sided die (used with the d10 to make a d100).

It is recommended to have two sets per player so that multi-dice rolls can occur at once.

Any die with a zero side is used as the max value for the die. For example, the zero on a d10 has a value of 10.

** Creating a Character

Use the following checklist to create a new character.

- Download a new character sheet
- Decide on a [[* Player Classes][player class]]
  - Fill in the class name
  - Fill in the starting stats assigned to your class
- Decide on a [[* Systems of Magic][magic system]] compatible with your player class
  - Fill in the magic system name
  - Fill in your starting spell choices
- Decide on a starting [[* Skills][skill]].
  - Fill in your starting skill
- Fill in your character name

* Combat

In combat, players and enemies take turns performing actions. A turn is broken up into one major action, one minor action, and as many as needed free actions. One is always free to use a minor action in place of a major action.

** Default Major Actions

*** Weapon Attack

Characters make an attack against an enemy using an equipped weapon. An unarmed attack can be made for 1 damage if no weapons are equipped.

*** Spell Cast

Characters who are learned in a [[* Systems of Magic][school of magic]] that provides spells marked as a major action can cast them.

*** Guard

Characters gain level / 2 [[* Defense][defense]] until the beginning of their next turn.

** Default Minor Actions

*** Movement

Characters move up to their [[* Movement Speed][movement speed]].

*** Swapping Held Items

Characters put away, replace, or take out items that can be used when held.

*** Reloading

Characters load ammunition into a ranged weapon, a bow for example.

** Conditions

*** Incapacitated

When a player drops below 0 HP, they become incapacitated. They are unable to take major or minor actions or regain HP normally.

Upon entering the state, they make a power [[* Ability Check][ability check]] (12). On a successful check, the character returns to 0 HP, and the effect ends at the end of the current fight. On a failed check, the character stays incapacitated until [[* Recovering][recovery]], and the character becomes afflicted by a [[* Grievous Wound][grievous wound]].

The condition can also be ended by a spell or item that provides the revive affect, returning the character to 1 HP and ending the effect, even during battle.

Every time a character is attacked while incapacitated, they suffer another [[* Grievous Wound][grievous wound]]. Some foes may ignore downed combatants, but not all are so merciful.

*** Death

Death is the end of your playable character. They have succumbed to their injuries and pass on to the final rest.

This is a good chance to say some final words to your comrades.

** Grievous Wound

When a character sustains critical injury, they become afflicted by a grievous wound. Roll a d6 to determine your characters grievous wound. This wounds cannot be removed by normal healing. If any grievous wound, except for Lucky Save, is rolled two times, then the character suffers [[* Death][death]].

*(1) Lucky Save*

Your character sees life flash before their eyes, but fortune favors the lucky. No negative effects are experienced.

*(2) Head Trauma*

The character is unable to remember people and motivations from their past. They must invent a new false backstory or find a new purpose.

*(3) Gnarly Scars*

The many wounds gained over time have accumulated and worn down the player. Their maximum [[* Health Points (HP)][HP]] is halved.

*(4) Damaged Arm*

Damage to one arm becomes too severe to save. Your character is no longer able to wield two handed equipment and can only wield one one handed equipment.

*(5) Damaged Leg*

Bone injuries have left the player with a worn gait. Their base [[* Movement Speed][movement speed]] is halved.

*(6) Death*

The character experiences [[* Death][death]].

** Recovering

Recovering is the process of regaining HP and MP. Certain classes regain additional resources while recovering.

*** Respite

A respite is the only recovery that can occur while out adventuring. A respite requires an uninterrupted rest of at least 4 hours. Spending 8 or more hours resting does not increase the resources gained, and a respite can only occur once a day.

After a respite, each player rolls a d6 up to their character level number of times. The players choose whether to add the value on the die rolled to their [[* Health Points (HP)][HP]] or [[* Magic Power (MP)][MP]].

Once character level number of respite dice have been rolled, no more can be rolled until a full recovery has occurred.

Respite can be modified by certain [[* Player Classes][classes]] and [[* Systems of Magic][magic systems]].

*** Full Recovery

A full recovery restores all of a character's [[* Health Points (HP)][HP]] and [[* Magic Power (MP)][MP]], but can only occur in [[* Towns][town]] over the period of a week. A full recovery will reset the number of respite dice rolled back to zero.

* Roleplaying

** Skills

Skills are trades that can be learned while in [[* Towns][town]] in order to augment a character's abilities. Skills take 3 months of time to learn and have an upfront cost.

*** Alchemy

*** Appraisal

*** Bow Training

*** Horseback Riding

*** Lockpicking

*** Shield Training

*** Smithing

** Ability Check

Ability checks are a way to use dice in combination with player stats to resolve an outcome.

The DM will ask for an ability check of a player for a particular [[* The Main Stats][main stat]]. It's the players job to roll a d12 and add their stat to the roll. It will then be up to the DM to resolve outcome.

** Dialog

Speaking with Non-Player Characters (NPCs) is a common part of adventuring. Players may wish to elicit information from a knowledgeable town resident, haggle on the price of a rare artifact, or convince an animal that they are friendly.

When players are expecting a result out of their conversation, it's the job of the DM to recognize this and ask for an [[* Ability Check][ability check]]. Players have many ways to be convincing, and the strength of their argument can have a great affect on the difficulty of the ability check.

Dialog is also one of the best ways to show off your character's personality!

* Character Stats

** Character Level

The level of your character is a measure of how skilled they are at their craft. This skill is manifested in additional stats, features, and magical ability.

Character level starts at 1 and goes up to 16. In order to level up, characters need to both gain experience out adventuring and spend time and money in [[* Towns][town]]. Your DM will let you know when you have gained enough experience to advance in level, but it is up to you to choose when to spend the time and money to learn the next level during [[* Town Actions][your town actions]].

At the 6th level, a study under a master is required. Masters are not uncommon, but are not found in every town. At the 11th level, a study under a grandmaster is required. Although most grandmasters are well known in story and legend, not all of them can be easy to find. In order to attain the 16th level, one has to advance their field beyond it's current limits. Work with your DM to discuss your plan for this, as such things do not come with a one size fits all price tag.

Use the following requirements chart to see what it takes to make it to level up. The monetary price to level up does not include [[* Living Expenses][living expenses]].

#+begin_xtable
| Level | Location          | Time     | Monetary Cost | Rank           |
|-------+-------------------+----------+---------------+----------------|
|     1 | N/A               | N/A      | N/A           | Apprentice     |
|     2 | Adventure Hall    | 1 month  | 100 Shells    | Apprentice II  |
|     3 | Adventure Hall    | 1 month  | 200 Shells    | Apprentice III |
|     4 | Adventure Hall    | 1 month  | 300 Shells    | Apprentice IV  |
|     5 | Adventure Hall    | 1 month  | 400 Shells    | Apprentice V   |
|     6 | Master Study      | 6 months | 1000 Shells   | Journeyman     |
|     7 | Adventure Hall    | 2 months | 1200 Shells   | Journeyman II  |
|     8 | Adventure Hall    | 2 months | 1400 Shells   | Journeyman III |
|     9 | Adventure Hall    | 2 months | 1600 Shells   | Journeyman IV  |
|    10 | Adventure Hall    | 2 months | 1800 Shells   | Journeyman V   |
|    11 | Grandmaster Study | 1 year   | 3000 Shells   | Master         |
|    12 | Adventure Hall    | 3 months | 3500 Shells   | Master II      |
|    13 | Adventure Hall    | 3 months | 4000 Shells   | Master III     |
|    14 | Adventure Hall    | 3 months | 4500 Shells   | Master IV      |
|    15 | Adventure Hall    | 3 months | 5000 Shells   | Master V       |
|    16 | ?                 | ?        | ?             | Grandmaster    |
#+end_xtable

** The Main Stats

Main stats are the primary stats in the game. Actions with an uncertain outcome are almost always modified by one of these through [[* Ability Check][ability checks]].

These stats range from 1 to 16. When stats are upgraded, the effects of stats are always retroactive. Stats are broken up into the following categories:

*** Power

/Power is used to express physical strength. Cleave, crush, and grapple your way through enemies./

Effects:

- Extra HP per level: Power / 4

*** Reflex

/Reflex measures your speed and reaction. Evade dangers and act before others. A high reflex shoots first./

Effects:

- Combat order: Higher reflex acts first

*** Focus

/Focus allows you to concentrate and understand complex concepts. Perceive the dangers around you and outwit opponents./

Effects:

- Extra MP per level: Focus / 4

*** Presence

/A high presence signifies awareness of the world around you. Anticipate the actions of others and make them pay for their predictability./

Effects:

- Critical strike chance: D20 roll <= Presence

** Auxiliary Stats

*** Health Points (HP)

Health points tracks the life of your character. The closer to 0, the closer your character is to [[* Death][death]]. Characters gain extra health at every level based on their [[* Player Classes][class]].

*** Magic Power (MP)

Magic power tracks the amount of magic that a character can perform. Characters gain extra health at every level based on their [[* Player Classes][class]].

*** Defense

Defense provides flat damage reduction.

*** Movement Speed

Movement speed is a measure how fast your character is. In [[* Combat][combat]], your character is allowed to move up to their movement speed in squares every round.

When moving diagonal, treat the first diagonal move as one square of movement, the second diagonal move as two squares of movement, then one, then two, etc.

* Towns

Towns provide a safe haven between adventures, a place to rest weary bones, and prepare for what's next.

** Living Expenses

Every month of time spent in town incurs living expenses. The price of these expenses depends upon your desired station. It may be tempting to choose meager living expenses, but know that you station effects how others perceive you. The rarest [[* Artifacts][artifacts]] and most lucrative jobs often go to those of high station. The prices for living expenses are shown in the following table.

#+begin_xtable
| Station | Monthly Expenses |
|---------+------------------|
| Meager  | 50 Shells        |
| Frugal  | 100 Shells       |
| Average | 200 Shells       |
| High    | 500 Shells       |
| Royal   | 1000 Shells      |
#+end_xtable

** Town Features

Towns support people from many walks of life. While in town you may wish to make use of services provided there. Not every town provides all of these services.

*** Adventure Hall

Adventure Halls are places where for hire adventurers can train and scout for work.

*** Apothecary

Apothecaries sell potions and droughts that may help you while you are away.

*** Cartographer

Cartographers are designers of maps. The more expensive ones are typically the more accurate.

*** Cobbler

Cobblers sell and repair footwear.

*** General Store

General Stores sell simple craft and imported goods.

*** Library

Libraries are rare and are usually tied to universities.

*** Market

Markets are areas, typically outdoors, where foods and crafts are sold.

*** Smithy

Smithies sell metal forged tools.

*** Stable

Stables house pack animals for a price. Some stables offer animals for sale.

*** Tailor

Tailors sell garments of various quality.

** Town Actions

You may be returning to town just for the sake of a [[* Full Recovery][full recovery]], but why not take advantage of what the town has to offer? Time spent in town is devoted to town actions. Town actions occur on the order of months, and each member of the party need not take the same town actions at the same time.

*** Learning Skills

Time in town can be spent learning a new [[* Skills][skill]]. See the list of skills for time and cost requirements.

*** Training

Time spent training at an [[* Adventure Hall][adventure hall]] allows you to [[* Character Level][level up]]. See the level up table for the time ranges and costs.

*** Mentorship

As your character gains levels, the ability to become a mentor assisting an unplayed character in leveling up becomes available. Players are responsible for creating a full character sheet for their mentee. A mentee must remain at least 5 levels lower than the player character.

Being a mentee takes time equal to the player character's . In exchange for your time and expertise, your character is rewarded with the price of [[* Character Level][level ups]] for the level the mentee gains. 

Mentees are not able to gain levels back to back. Just like players, they need time to develop their new knowledge. This amount of time is at the DM's discretion.

Mentees may wish to join your adventuring party at such unfortunate times that room becomes available...

*** Philanthropy

Many organizations rely on the generosity of rich adventurers. You may wish to spend time donating funds or volunteering for an organization that your character is aligned with.

*** Research

Time can be spent researching a topic in town. Asking around, checking scholarly records. Some research tasks can go easier with a little grease.

*** Shopping

Adventuring requires extreme preparation. Before embarking, it is wise to stock up on items to help you while away.

*** Working

Taking up temporary work allows you to live with frugal [[* Living Expenses][expenses]] without costing any gold. Performing skilled labor may pay for higher expenses and the DM's discretion.

* Player Classes

** Tactician

Tacticians are able to survey a battlefield with ease. They are able to command allies, increasing their battle effectiveness, and have insight into enemies traits.

HP per Level: 8

MP per Level: 8

One standard magic system.

At the first level, tacticians gain the *delayed action* class feature. This allows the player to take their minor action, major action, or both actions later in the turn order. The conditions for taking the turn and the action that is to be taken must be expressed during your normal turn.

At the third level, tacticians gain the *battle insight* minor action. This lets the tactician determine either the remaining [[* Health Points (HP)][HP]] of a single enemy, the current [[* Defense][defense]] of a single enemy, or the damage weaknesses of a single enemy.

At the fifth level, tacticians gain the *dual guard* major action. If an ally is within five feet of the tactician, both they and the tactician gain the effect of the guard. This can only affect one ally per turn, and that ally cannot benefit from a guard of their own on the same turn.

At the seventh level, tacticians gain the *exploited habits* class feature. Attacks against armored opponents ignore [[* Presence][presence]] / 4 defense.

At the ninth level, tacticians gain the *minor shot calling* minor action. This lets another player character take a minor action during your turn instead of you. You decide who and which minor action, but the other player must agree with your choice.

At the eleventh level, tacticians gain the *major shot calling* major action. This lets another player character take a major action during your turn instead of you. You decide who and which major action, but the other player must agree with your choice.

At the thirteenth level, tacticians gain the

At the fifteenth level, tacticians gain the

At the sixteenth level, tacticians gain the *battle commander* class feature. This lets another player character take both a major and minor action on your turn in addition to you. You decide who and which actions, but the other player must agree with your choice.

** Mercenary

Mercenaries are masters of combat and weaponry, able to wield the rarest weapons and strongest armors. Cleaving and rending is the way of the Mercenary.

HP per Level: 10
MP per Level: 6

One standard magic system.

At the first level, mercenaries gain the
At the third level, mercenaries gain the
At the fifth level, mercenaries gain the
At the seventh level, mercenaries gain the
At the ninth level, mercenaries gain the
At the eleventh level, mercenaries gain the
At the thirteenth level, mercenaries gain the
At the fifteenth level, mercenaries gain the
At the sixteenth level, mercenaries gain the

** Assassin

Assassins are skilled dealing damage through the use of well placed attacks and devious weapon modifications. Few can stand before an Assassin and live to tell the tale.

HP per Level: 8
MP per Level: 8

One standard magic system.

At the first level, assassins gain the
At the third level, assassins gain the
At the fifth level, assassins gain the
At the seventh level, assassins gain the
At the ninth level, assassins gain the
At the eleventh level, assassins gain the
At the thirteenth level, assassins gain the
At the fifteenth level, assassins gain the
At the sixteenth level, assassins gain the

** Scholar

Scholars are those who seek to understand the titan's influence on the world. The knowledge is only a mimicry, but even a fraction of that power is enough to demand respect.

HP per Level: 6
MP per Level: 10

One advanced magic system.

At the first level, scholars gain the
At the third level, scholars gain the
At the fifth level, scholars gain the
At the seventh level, scholars gain the
At the ninth level, scholars gain the
At the eleventh level, scholars gain the
At the thirteenth level, scholars gain the
At the fifteenth level, scholars gain the
At the sixteenth level, scholars gain the

** Bereft

The Bereft are those without any advantage in life. Unlikely adventurers, but it is not for fate to say who are the greats.

HP per Level: 8
MP per Level: 3

No magic systems.

* Systems of Magic

The power of the titans left its mark on the world. The study of these marks led to the beginning of the practice of magic. Independently, the studies led in different paths that lead to the groups of magic that are currently known.

Each group requires a lifetime of practice and a focus to the craft. Even then, some advanced magics are only able to be learned by those who give their complete energy to the study. These are known as advanced magics, while the easier magics are called the standard magics.

** Runecast

*Type*: Standard

The Runecast are warriors that pursue the study of an ancient written language. By etching these runic symbols into their weapons and armor, they are able to bind the power of magic to physical objects, and augment their combat ability.

Carving runes into your weapons and armor reserves [[* Magic Power (MP)][MP]]. The passive effects of these runes are always present. Runecast are only able to modify their own equipment and can not add runes to [[* Artifacts][artifacts]].

The number of runes that can be equipped at a time is shown in the following table.

#+begin_xtable
| Level | # of Runes |
|-------+------------|
|     1 | 1          |
|     2 | 2          |
|     3 | 2          |
|     4 | 3          |
|     5 | 3          |
|     6 | 4          |
|     7 | 4          |
|     8 | 5          |
|     9 | 5          |
|    10 | 6          |
|    11 | 6          |
|    12 | 7          |
|    13 | 7          |
|    14 | 8          |
|    15 | 8          |
|    16 | 10         |
#+end_xtable

** Spirit Caller

*Type*: Standard

Spirit Callers hold a spiritual bond with their ancestors. In death, the spirits of the departed are able to impart their favors upon the physical world.

These effects are limited by the number of favors available and can be activated a number of times per combat shown in the following table.

#+begin_xtable
| Level | # Casts Per Combat | # Favors Available |
|-------+--------------------+--------------------|
|     1 |                  1 |                  1 |
|     2 |                  2 |                  2 |
|     3 |                  2 |                  2 |
|     4 |                  2 |                  3 |
|     5 |                  2 |                  3 |
|     6 |                  3 |                  4 |
|     7 |                  3 |                  4 |
|     8 |                  3 |                  5 |
|     9 |                  3 |                  5 |
|    10 |                  3 |                  6 |
|    11 |                  4 |                  6 |
|    12 |                  4 |                  7 |
|    13 |                  4 |                  7 |
|    14 |                  4 |                  8 |
|    15 |                  4 |                  8 |
|    16 |                  5 |                 10 |
#+end_xtable

** Harvester

*Type*: Standard

Harvesters utilize the remains of the fallen, twisting them to their own purposes. They collect soul pieces from those that die during combat, which are manipulated to their end through the use of spells called extractions.

The number of known extractions and maximum number of should pieces that can be held at the same time are shown in the following table.

#+begin_xtable
| Level | # Extractions Known | Max Soul Pieces |
|-------+---------------------+-----------------|
|     1 |                   1 |               3 |
|     2 |                   2 |               4 |
|     3 |                   2 |               4 |
|     4 |                   3 |               5 |
|     5 |                   3 |               5 |
|     6 |                   4 |               6 |
|     7 |                   4 |               6 |
|     8 |                   5 |               7 |
|     9 |                   5 |               7 |
|    10 |                   6 |               8 |
|    11 |                   6 |               8 |
|    12 |                   7 |               9 |
|    13 |                   7 |               9 |
|    14 |                   8 |              10 |
|    15 |                   8 |              10 |
|    16 |                  10 |              12 |
#+end_xtable

** Wildpact

*Type*: Standard

Wildpact are those who have formed a magical bond with a beast companion. Time spent in the wilds has formed a shared consciousness that allows the wildpact and beast to fight as one.

** Ancient Whisperer

*Type*: Advanced

The Ancient Whisperers have studied the lost spoken language of the titans. Through great mental exertion, they can recall incantations the forgotten language, shaping the world as the titans once did.

The number of known incantations are shown in the following table.

#+begin_xtable
| Level | # Incantations Known |
|-------+----------------------|
|     1 |                    1 |
|     2 |                    2 |
|     3 |                    3 |
|     4 |                    4 |
|     5 |                    5 |
|     6 |                    6 |
|     7 |                    7 |
|     8 |                    8 |
|     9 |                    9 |
|    10 |                   10 |
|    11 |                   11 |
|    12 |                   12 |
|    13 |                   13 |
|    14 |                   14 |
|    15 |                   15 |
|    16 |                   16 |
#+end_xtable

** Elementalist

*Type*: Advanced

Elementalists draw from the latent magic left behind from the construction of the world.

Elemental spells, called sourceries, can be devastatingly powerful, but rely on the setup and maintenance of elemental catalysts. Elementalists learn major and minor sourceries that can be used as major and minor actions.

Elementalists work with the catalysts of heat, cold, earth, lightning, and dark.  Sourceries that create these catalysts are marked with a type and amount, e.g. creates heat 2. Spells that consume the catalysts are marked with type and cost, e.g. consumes heat 1. At the end of the elementalist's turn, the value of each catalyst type is reduced by 1 to a minimum of 0.

#+begin_xtable
| Level | # Major Sourceries Known | # Minor Sourceries Known |
|-------+--------------------------+--------------------------|
|     1 |                        1 |                        1 |
|     2 |                        2 |                        2 |
|     3 |                        3 |                        2 |
|     4 |                        4 |                        2 |
|     5 |                        5 |                        2 |
|     6 |                        6 |                        3 |
|     7 |                        7 |                        3 |
|     8 |                        8 |                        3 |
|     9 |                        9 |                        3 |
|    10 |                       10 |                        3 |
|    11 |                       11 |                        4 |
|    12 |                       12 |                        4 |
|    13 |                       13 |                        4 |
|    14 |                       14 |                        4 |
|    15 |                       15 |                        4 |
|    16 |                       16 |                        5 |
#+end_xtable

* Equipment

** Currency

The currency in the game are shells and pearls.

#+begin_xtable
| Currency     | Value (in Shells) |
|--------------+-------------------|
| Shells       |                 1 |
| Pearls       |               100 |
| Black Pearls |              1000 |
#+end_xtable

** Combat Equipment

Combat equipment includes weapons, armor, helms, and shields.

Armor and helms are considered worn equipment. Weapons and shields are considered held equipment.

Only one set of armor and one helm can be worn at a time. Two one-handed combat items or one two-handed combat items can be worn at a time.

Switching held equipment, can done with the [[* Swapping Held Items][swapping held items]] minor action.

** Adventuring Equipment

In addition to combat equipment, it is wise to stock up on adventuring equipment. These include ropes, light sources, bags, etc.

** Potions

Potions can be bought at an [[* Apothecary][apothecary]]. Potions are described as simple or complicated.

** Artifacts

Artifacts are special items infused with great power. Artifacts can be of any item type, but are always better than the base item. Artifacts may have requirements beyond the base item.

Artifacts are valuable and coveted, so to have any is to paint a target on your back. Guard them carefully.

-----

#+begin_cw
Copyright \copy 2021, William Goubeaux
#+end_cw
