#+Title: Of Wilds and Wastes TTRPG

* Introduction

** World of Wilds and Wastes
The world of Of Wilds and Wastes began with the titans. The colossal beings used might and magic to shear the plains flat, heat the core of the planet, and gift the world with water and sun. Today, their fossilized remains are strewn about the world in hidden groves. Nobody knows how they came to die, but legend says that they gave up their power willingly, to share their earthen canvas with the rest of life's creatures.

Without the chaos of the titan's ongoing construction, the creatures 
of the world were allowed to grow and evolve. With enough time, the lands became overgrown with all manner of beast. Intelligence alone was not enough to live at the top of the food chain, so lowly humans were relegated to hiding and building what defenses they could, praying that their independent settlements not fall victim to ruin.

But the world is beginning to change once again. Humans are uncovering the magic that the titans left behind. With this newfound power, they are striking out, exploring the world, and trading with others for the first time. It is in this setting that Of Wilds and Wastes takes place. There is high demand for those who can defend against the wilds. The best adventurers of the world are renowned and exalted, but not many of them are very wrinkled...

** What is needed to play

Of Wilds and Wastes is meant to be played with two or more players. The sweet spot is 3 to 5 players and another player be the master of ceremonies, abbreviated MC from here on out.

* Combat

In combat, players and enemies take turns performing actions. A turn is broken up into one major action, one minor action, and as many as needed free actions. One is always free to use a minor action in place of a major action.

** Default Major Actions

*** Weapon Attack

Characters make an attack against an enemy using an equipped weapon. An unarmed attack can be made for 1 damage if no weapons are equipped.

*** Spell Cast

Characters who are learned in a [[*Systems of Magic][school of magic]] that provides castable spells may do so as a major action.

** Default Minor Actions

*** Movement

Characters move up to their [[*Movement Speed][movement speed]].

*** Swapping Held Items

Characters put away, replace, or take out items that can be used when held.

*** Reloading

Characters load ammunition into a ranged weapon, a bow for example.

** Example Turns

* Character Stats

Character stats range from 1 to 16. When stats are upgraded, the effects of stats are always retroactive. Stats are broken up into the following categories:

** The Main Stats

These stats are the primary stats in the game. Actions with an uncertain outcome are almost always modified by one of these.

*** Power

/Power is used to express physical strength. Cleave, crush, and grapple your way through enemies./

Effects:

- Extra HP per level: Power / 4

*** Reflex

/Reflex measures your speed and reaction. Evade dangers and act before others. A high reflex shoots first./

Effects:

- Combat order: Higher reflex acts first

*** Focus

/Focus allows you to concentrate and understand complex concepts. Perceive the dangers around you and outwit opponents./

Effects:

- Extra MP per level: Focus / 4

*** Presence

/A high presense signifies awareness of the world around you. Anticipate the actions of others and make them pay for their predictability./

Effects:

- Critical strike chance: D20 roll <= Presence

** Auxiliary Stats

*** Health Points (HP)

*** Magic Power (MP)

*** Movement Speed

* Player Classes

** Tactician

/"Victory requires no hope, it is assured."/

Tacticians are able to survey a battlefield with ease. They are able to command allies, increasing their battle effectiveness, and have insight into enemies traits.

HP per Level: 8
MP per Level: 8
One minor magic system

** Mercenary

/"Imagine bringing a pen to battle."/

Mercenaries are masters of combat and weaponry, able to wield the rarest weapons and strongest armors. Cleaving and rending is the way of the Mercenary.

HP per Level: 10
MP per Level: 6
One minor magic system

** Assassin

/"How easy one slips into the long dark."/

Assassins are skilled dealing damage through the use of well placed attacks and devious weapon modifications. Few can stand before an Assassin and live to tell the tale.

HP per Level: 8
HP per Level: 8
One minor magic system


** Scholar

/"To seek no knowledge is to squander life and live as does the commonest weed."/

Scholars are those who seek to understand the titan's influence on the world. The knowledge is only a mimicry, but even a fraction of that power is enough to demand respect.

HP per Level: 6
HP per Level: 10
One major magic system and one minor magic system

** Beastheart

/"Roar."/

Beasthearts are those who have formed a strong bond with a beast of nature. Time spent in the wilds has formed a shared consciousness with the beathearts closest animal companion.

** Bereft

/"Passed by without so much as a glance."/

The Bereft are those without any advantage. Unlikely adventurers, but it is not for fate to say who are the greats.

HP per Level: 6
MP per Level: 0

* Systems of Magic

** Minor Magics

*** Runecast
The Runecast are warriors that pursue the study of the ancient written language of the titans. By etching these runic symbols into their weapons and armor, they are able to augment their combat ability.

*** Spirit Caller
Spirit Callers hold a spiritual bond with the titans. In death, the titans retain the ability to influence the world through the desires of those who can call to them.

*** Harvester
Harvesters utilize the remains of titans to extract power from the carcasses of monsters twisting them to their own purposes.

** Major Magics

*** Ancient Whisperer
The Ancient Whisperers have studied the spoken language of the titans. Through great mental exertion, they can recall the forgotten language of the titans shaping the world as the titans once did.

*** Elementalist
Elementalists draw from the latent magic left behind the construction of the world.

** Other Magics

*** Weird
Some phenomenon are without explanation. Whatever was there to wind the clock of time for the first time, indifferent to the world that was set in motion, can sometimes leave its traces on the world's denizens. It's unknown why this happens, but the effect are striking.

* Equipment Classes
