#+Title: Of Wilds and Wastes TTRPG

* Introduction

** World of Wilds and Wastes
The world of Of Wilds and Wastes began with the titans. The colossal beings used might and magic to shear the plains flat, heat the core of the planet, and gift the world with water and sun. Today, their fossilized remains are strewn about the world in hidden groves. Nobody knows how they came to die, but legend says that they gave up their power willingly, to share their earthen canvas with the rest of life's creatures.

Without the chaos of the titan's ongoing construction, the creatures of the world were allowed to grow and evolve. With enough time, the lands became overgrown with all manner of beast. Intelligence alone was not enough to live at the top of the food chain, so lowly humans were relegated to hiding and building what defenses they could, praying that their independent settlements not fall victim to ruin.

But the world is beginning to change once again. Humans are uncovering the magic that the titans left behind. With this newfound power, they are striking out, exploring the world, and trading with others for the first time. It is in this setting that Of Wilds and Wastes takes place. There is high demand for those who can defend against the wilds. The best adventurers of the world are renowned and exalted, but not many of them are very wrinkled...

** What is needed to play

Of Wilds and Wastes is meant to be played with two or more players. The sweet spot is 3 to 5 players and another player be the Game Master, abbreviated GM from here on out.

Each player requires one full set of RPG dice: a four sided die (d4), a six sided die (d6), a ten sided die (d10), a twelve sided die (d12), a twenty sided die (d20), and a tens marked ten sided die (used with the d10 to make a d100).

It is recommended to have two sets per player so that multi-dice rolls can occur at once.

Any die with a zero side is used as the max value for the die. For example, the zero on a d10 has a value of 10.

** Creating a Character

Use the following checklist to create a new character.

- Download a new character sheet
- Decide on a [[* Player Classes][player class]]
  - Fill in the class name
  - Fill in the starting stats assigned to your class
- Decide on a [[* Systems of Magic][magic system]] compatible with your player class
  - Fill in the magic system name
  - Fill in your starting spell choices
- Decide on a starting skill
  - Fill in your starting skill
- Fill in your character name

* Combat

In combat, players and enemies take turns performing actions. A turn is broken up into one major action, one minor action, and as many as needed free actions. One is always free to use a minor action in place of a major action.

** Default Major Actions

*** Weapon Attack

Characters make an attack against an enemy using an equipped weapon. An unarmed attack can be made for 1 damage if no weapons are equipped.

*** Spell Cast

Characters who are learned in a [[* Systems of Magic][school of magic]] that provides spells marked as a major action can cast them as such.

** Default Minor Actions

*** Movement

Characters move up to their [[* Movement Speed][movement speed]].

*** Swapping Held Items

Characters put away, replace, or take out items that can be used when held.

*** Reloading

Characters load ammunition into a ranged weapon, a bow for example.

** Conditions

*** Incapacitated

When a player drops below 0 HP, they become incapacitated. They are unable to take major or minor actions or regain HP normally.

Upon entering the state, they make a power [[* Ability Check][ability check]] (12). On a successful check, the character returns to 0 HP, and the effect ends at the end of the current fight. On a failed check, the character stays incapacitated until [[* Recovery][recovery]], and the character becomes afflicted by a [[* Grevious Wound][grevious wound]].

The condition can also be ended by a spell or item that provides the revive affect, returning the character to 1 HP and ending the effect, even during battle.

Every time a character is attacked while incapacitated, they suffer another [[* Grevious Wound][grevious wound]]. Some foes may ignore downed combatants, but not all are so merciful.

*** Death

Death is the end of your playable character. They have succumbed to their injuries and pass on to the final rest.

This is a good chance to say some final words to inspire your comrades. It is customary to hold a ceremony for the fallen upon return to settlement.

** Grievous Wound

When a character sustains critical injury, they become afflicted by a grievous wound. Roll a d6 to determine your characters grievous wound. This wounds cannot be removed by normal healing. If the same grievous wound is rolled two times in a row, then the character suffers [[* Death][death]].

*** (1) Head Trauma

The character is unable to remember people and motivations from their past. They must invent a new false backstory or find a new purpose.

*** (2) Missing Arm

Damage to one arm becomes too severe to save. Your character is no longer able to wield two handed equipment and can only wield one one handed equipment.

*** (3) Severed Magical Connection

Injuries the body sever the connection a player has with their school of magic. Their [[* Magic Power (MP)][MP]] is halved.

*** (4) Gnarly Scars

The many wounds gained over time have accumulated and worn down the player. Their maximum [[* Health Points (HP)][HP]] is halved.

*** (5) Unset Fracture

Bone injuries have left the player with a worn gait. Their base [[* Movement Speed][movement speed]] is halved.

*** (6) Death

The character experiences [[* Death][death]].

** Recovering

Recovering is the process of regaining HP and MP. Certain classes regain additional resources while recovering.

*** Respite

A respite is the only recovery that can occur while out adventuring. After a respite, each player rolls a d6 for every character level. The players choose whether to 

A respite requires an uninterrupted rest of at least 4 hours. Spending 8 or more hours resting does not increase the resources gained. A respite can only occur once a day.

*** Full Recovery

A full recovery restores all of a character's [[* Health Points (HP)][HP]] and [[* Magic Power (MP)][MP]], but can only occur in [[* Towns][town]].


* Roleplaying

** Ability Check

Ability checks are a way to use dice in combination with player stats to resolve an outcome.

The DM will ask for an ability check of a player for a particular [[** The Main Stats][main stat]]. It's the players job to roll a d12 and add their stat to the roll. It will then be up to the DM to resolve outcome.

** Dialog

Speaking with Non-Player Characters (NPCs) is a common part of adventuring. Players may wish to elicit information from a knowledgeable town resident, haggle on the price of a rare artifact, or convince an animal that they are friendly.

When players are expecting a result out of their conversation, it's the job of the DM to detect this and ask for an [[* Ability Check][ability check]]. Players have many ways to be convincing, and the strength of their argument can have a great affect on the difficulty of the ability check.

Dialog is also one of the best ways to show off your character!

* Character Stats

Character stats range from 1 to 16. When stats are upgraded, the effects of stats are always retroactive. Stats are broken up into the following categories:

** The Main Stats

These stats are the primary stats in the game. Actions with an uncertain outcome are almost always modified by one of these.

*** Power

/Power is used to express physical strength. Cleave, crush, and grapple your way through enemies./

Effects:

- Extra HP per level: Power / 4

*** Reflex

/Reflex measures your speed and reaction. Evade dangers and act before others. A high reflex shoots first./

Effects:

- Combat order: Higher reflex acts first

*** Focus

/Focus allows you to concentrate and understand complex concepts. Perceive the dangers around you and outwit opponents./

Effects:

- Extra MP per level: Focus / 4

*** Presence

/A high presence signifies awareness of the world around you. Anticipate the actions of others and make them pay for their predictability./

Effects:

- Critical strike chance: D20 roll <= Presence

** Auxiliary Stats

*** Health Points (HP)

Health points tracks the life of your character. The closer to 0, the closer your character is to [[* Death][death]]. Characters gain extra health at every level based on their [[* Player Classes][class]].

*** Magic Power (MP)

Magic power tracks the amount of magic that a character can perform. Characters gain extra health at every level based on their [[* Player Classes][class]].

*** Movement Speed

Movement speed is a measure how fast your character is. In [[* Combat][combat]], your character is allowed to move up to their movement speed in squares every round.

When moving diagonal, treat the first diagonal move as one square of movement, the second diagonal move as two squares of movement, then one, then two, etc.

* Combat

In combat, players and enemies take turns performing actions. A turn is broken up into one major action, one minor action, and as many as needed free actions. One is always free to use a minor action in place of a major action.

** Default Major Actions

*** Weapon Attack

Characters make an attack against an enemy using an equipped weapon. An unarmed attack can be made for 1 damage if no weapons are equipped.

*** Spell Cast

Characters who are learned in a [[* Systems of Magic][school of magic]] that provides spells marked as a major action can cast them as such.

** Default Minor Actions

*** Movement

Characters move up to their [[* Movement Speed][movement speed]].

*** Swapping Held Items

Characters put away, replace, or take out items that can be used when held.

*** Reloading

Characters load ammunition into a ranged weapon, a bow for example.

** Conditions

*** Incapacitated

When a player drops below 0 HP, they become incapacitated. They are unable to take major or minor actions or regain HP normally.

Upon entering the state, they make a power [[* Ability Check][ability check]] (12). On a successful check, the character returns to 0 HP, and the effect ends at the end of the current fight. On a failed check, the character stays incapacitated until [[* Recovery][recovery]], and the character becomes afflicted by a [[* Grevious Wound][grevious wound]].

The condition can also be ended by a spell or item that provides the revive affect, returning the character to 1 HP and ending the effect, even during battle.

Every time a character is attacked while incapacitated, they suffer another [[* Grevious Wound][grevious wound]]. Some foes may ignore downed combatants, but not all are so merciful.

*** Death

Death is the end of your playable character. They have succumbed to their injuries and pass on to the final rest.

This is a good chance to say some final words to inspire your comrades. It is customary to hold a ceremony for the fallen upon return to settlement.

** Grievous Wound

When a character sustains critical injury, they become afflicted by a grievous wound. Roll a d6 to determine your characters grievous wound. This wounds cannot be removed by normal healing. If the same grievous wound is rolled two times in a row, then the character suffers [[* Death][death]].

*** (1) Head Trauma

The character is unable to remember people and motivations from their past. They must invent a new false backstory or find a new purpose.

*** (2) Missing Arm

Damage to one arm becomes too severe to save. Your character is no longer able to wield two handed equipment and can only wield one one handed equipment.

*** (3) Severed Magical Connection

Injuries the the body sever the connection a player has with their school of magic. Their [[* Magic Power (MP)][MP]] is halved.

*** (4) Gnarly Scars

The many wounds gained over time have accumulated and worn down the player. Their maximum [[* Health Points (HP)][HP]] is halved.

*** (5) Unset Fracture

Bone injuries have left the player with a worn gait. Their base [[* Movement Speed][movement speed]] is halved.

*** (6) Death

The character experiences [[* Death][death]].

** Recovering

Recovering is the process of regaining HP and MP. Certain classes regain additional resources while recovering.

*** Respite

A respite is the only recovery that can occur while out adventuring. After a respite, each player rolls a d6 for every character level. The players choose whether to 

A respite requires an uninterrupted rest of at least 4 hours. Spending 8 or more hours resting does not increase the resources gained. A respite can only occur once a day.

*** Full Recovery

A full recovery restores all of a character's [[* Health Points (HP)][HP]] and [[* Magic Power (MP)][MP]], but can only occur in [[* Towns][town]].

* Towns

** Spending Time

* Player Classes

** Tactician

/"Victory requires no hope, it is assured."/

Tacticians are able to survey a battlefield with ease. They are able to command allies, increasing their battle effectiveness, and have insight into enemies traits.

HP per Level: 8
MP per Level: 8
One standard magic system

** Mercenary

/"Imagine bringing a pen to battle."/

Mercenaries are masters of combat and weaponry, able to wield the rarest weapons and strongest armors. Cleaving and rending is the way of the Mercenary.

HP per Level: 10
MP per Level: 6
One standard magic system

** Assassin

/"How easy one slips into the long dark."/

Assassins are skilled dealing damage through the use of well placed attacks and devious weapon modifications. Few can stand before an Assassin and live to tell the tale.

HP per Level: 8
HP per Level: 8
One standard magic system

** Scholar

/"To seek no knowledge is to squander life and live as does the commonest weed."/

Scholars are those who seek to understand the titan's influence on the world. The knowledge is only a mimicry, but even a fraction of that power is enough to demand respect.

HP per Level: 6
HP per Level: 10
One advanced magic system

** Beastheart

/"Roar."/

Beasthearts are those who have formed a strong bond with a beast of nature. Time spent in the wilds has formed a shared consciousness with the beastheart's closest animal companion.

** Bereft

/"Passed by without so much as a glance."/

The Bereft are those without any advantage. Unlikely adventurers, but it is not for fate to say who are the greats.

HP per Level: 6
MP per Level: 0

* Systems of Magic

** Standard Magics

*** Runecast
The Runecast are warriors that pursue the study of the ancient written language of the titans. By etching these runic symbols into their weapons and armor, they are able to augment their combat ability.

Carving runes into your weapons and armor reserves [[* Magic Power (MP)][mp]]. The passive effects of these runes are always present.

*** Spirit Caller
Spirit Callers hold a spiritual bond with their ancestors. In death, the titans retain the ability to influence the world through the favor given by the spirits of the departed. Spirit Callers call upon their predecessors to vouch for them.

*** Harvester
Harvesters utilize the remains of titans to extract power from the carcasses of monsters twisting them to their own purposes.

*** Weird
Some phenomenon are without explanation. Whatever was there to wind the clock of time for the first time, indifferent to the world that was set in motion, can sometimes leave its traces on the world's denizens. It's unknown why this happens, but the effect are striking.

** Advanced Magics

*** Ancient Whisperer
The Ancient Whisperers have studied the spoken language of the titans. Through great mental exertion, they can recall the forgotten language of the titans shaping the world as the titans once did.

*** Elementalist
Elementalists draw from the latent magic left behind from the construction of the world.

Elemental spells can be devastatingly powerful, but rely on the setup and maintenance of elemental catalysts. [[* Magic Power (MP)][mp]] is expended to harness these forces in large scale attacks.

* Equipment Classes
