#+Title: Of Wilds and Wastes TTRPG

* Introduction

** World of Wilds and Wastes
The world of Of Wilds and Wastes began with the titans. The colossal beings used might and magic to shear the plains flat, heat the core of the planet, and gift the world with water and sun. Today, their fossilized remains are strewn about the world in hidden groves. Nobody knows how they came to die, but legend says that they gave up their power willingly, to share their earthen canvas with the rest of life's creatures.

Without the chaos of the titan's ongoing construction, the creatures 
of the world were allowed to grow and evolve. With enough time, the lands became overgrown with all manner of beast. Intelligence alone was not enough to live at the top of the food chain, so lowly humans were relegated to hiding and building what defenses they could, praying that their independent settlements not fall victim to ruin.

But the world is beginning to change once again. Humans are uncovering the magic that the titans left behind. With this newfound power, they are striking out, exploring the world, and trading with others for the first time. It is in this setting that Of Wilds and Wastes takes place. There is high demand for those who can defend against the wilds. The best adventurers of the world are renowned and exalted, but not many of them are very wrinkled...

** What is needed to play

Of Wilds and Wastes is meant to be played with two or more players. The sweet spot is 3 to 5 players and another player be the master of ceremonies, abbreviated MC from here on out.

* Combat

* Character Stats

Character stats range from 1 to 16. When stats are upgraded, the effects of stats are always retroactive. Stats are broken up into the following categories:

** Power

/Power is used to express physical strength. Cleave, crush, and grapple your way through enemies./

Effects:

- Extra HP per level: Power / 4

** Reflex

/Reflex measures your speed and reaction. Evade dangers and act before others. A high reflex shoots first./

Effects:

- Combat order: Higher reflex acts first

** Focus

/Focus allows you to concentrate and understand complex concepts. Perceive the dangers around you and outwit opponents./

Effects:

- Extra MP per level: Focus / 4

** Presence

/A high presense signifies awareness of the world around you. Anticipate the actions of others and make them pay for their predictability./

Effects:

- Critical strike chance: D20 roll <= Presence

* Player Classes

** Tactician

/"Victory requires no hope, it is assured."/

HP per Level: 8
MP per Level: 8
One minor magic system

** Mercenary

/"Imagine bringing a pen to battle."/

Mercenaries are masters of combat and weaponry. Able to wield the rarest weapons and strongest armors. Of all the classes to take up adventuring, mercenaries know best what they are in for.

HP per Level: 10
MP per Level: 6
One minor magic system

** Assassin

/"How easy one slips into the long dark."/

HP per Level: 8
HP per Level: 8
One minor magic system

** Fatebound

/"Meow."/


HP per Level: 8
MP per Level: 10
One minor magic system

** Scholar

/"To seek no knowledge is to squander life and live as does the commonest weed."/

HP per Level: 6
HP per Level: 10
One major magic system and one minor magic system

** Bereft

/"Passed by without so much as a glance."/

HP per Level: 6
MP per Level: 0

* Systems of Magic

** Minor Magics

*** Runecast
The Runecast are warriors that pursue the study of the ancient written language of the titans. By etching these runic symbols into their weapons and armor, they are able to augment their combat ability.

*** Spirit Caller
Spirit Callers hold a spiritual bond with the titans. In death, the titans retain the ability to influence the world through the desires of those who can call to them.

*** Harvester
Harvesters utilize the remains of titans to extract power from the carcasses of monsters twisting them to their own purposes.

** Major Magics

*** Ancient Whisperer
The Ancient Whisperers have studied the spoken language of the titans. Through great mental exertion, they can recall the forgotten language of the titans shaping the world as the titans once did.

*** Elementalist
Elementalists draw from the latent magic left behind the construction of the world.

** Other Magics

*** Weird
Some phenomenon are without explanation. Whatever was there to wind the clock of time for the first time, indifferent to the world that was set in motion, can sometimes leave its traces on the world's denizens. It's unknown why this happens, but the effect are striking.

* Equipment Classes
