#+Title: Calypso TTRPG

* Introduction

** World of Calypso
The world of Calypso began with the titans. The colossal beings used might and magic to shear the plains flat, heat the core of the planet, and gift the world with water and sun. Today, their fossilized remains are strewn about the world in hidden groves. Nobody knows how they came to die, but legend says that they gave up their power willingly, to share their earthen canvas with the rest of life's creatures.

Without the chaos of the titan's ongoing construction, the creatures 
of the world were allowed to grow and evolve. With enough time, the lands became overgrown with all manner of beast. Intelligence alone was not enough to live at the top of the food chain, so lowly humans were relegated to hiding and building what defenses they could, praying that their independent settlements not fall victim to ruin.

But the world is beginning to change once again. Humans are uncovering the magic that the titans left behind. With this newfound power, they are striking out, exploring the world, and trading with others for the first time. It is in this setting that Calypso takes place. There is high demand for those who can defend against the wilds. The best adventurers of the world are renowned and exalted, but not many of them are very wrinkled...

** Tenants of Calypso
*** Combat turns should feel impactful
Imagine the following scenario:

You find yourself in the midst of battle. Like most adventurers, your goal is to defeat your enemies spectacular and show off your prowess in combat. As an experienced fighter, you have slain innumerable enemies. You ready your attack and miss. That is your action, so you end your turn. You already are expecting to perform the same action next turn.

Turns like this drag down one of the core tenants of many TTRPGs, and incidentally, this core tenant is the one that the handbooks go into the most detail describing.

Calypso aims to solve the boring turn problem with actions that are always impactful. Players should not end a turn without feeling like nothing was accomplished.
*** Classes are useful at all levels
Every class should be fun to play and no party member should be eclipsed by another.
*** Encounters should be fun to prepare by being easy to design
Calypso strives for the following.
- In person sessions should be able to be ran without electronic assistance.
- GM preparation should not be limited by paper medium. Statistics for the creatures of Calypso are in a format that computers can read. No more page flipping or copying of information is required.
*** All players are human
The setting of Calypso takes place in the fledgling cradle of human civilization, and humans nature is varied enough to support nearly any character type. Because of this, players always start out as a human. That is not to say that other peoples do not occupy the lands of Calypso, but their existence and nature is known only the GM.

** What is needed to play

Calpyso is meant to be played with two or more players. The sweet spot is 3 to 5 players.

* Combat

* Character Stats

Character stats range from 1 to 16. When stats are upgraded, the effects of stats are always retroactive. Stats are broken up into the following categories:

** Power

/Power is used to express physical strength. Cleave, crush, and grapple your way through enemies./

Effects:

- Extra HP per level: Power / 4

** Reflex

/Reflex measures your speed and reaction. Evade dangers and act before others. A high reflex shoots first./

Effects:

- Combat order: Higher reflex acts first

** Focus

/Focus allows you to concentrate and understand complex concepts. Perceive the dangers around you and outwit opponents./

Effects:

- Extra MP per level: Focus / 4

** Presence

/A high presense signifies awareness of the world around you. Anticipate the actions of others and make them pay for their predictability./

Effects:

- Critical strike chance: D20 roll <= Presence

* Player Classes

** Warrior

HP per Level: 10
MP per Level: 8
One minor magic system

** Mercenary
HP per Level: 10
MP per Level: 6
One minor magic system

** Assassin
HP per Level: 8
HP per Level: 8
One minor magic system

** Scholar
HP per Level: 6
HP per Level: 10
One major magic system and one minor magic system

** Witch Doctor
HP per Level: 8
MP per Level: 10
One major magic system and one minor magic system

** Bereft
HP per Level: 6
MP per Level: 0
Magic Systems: Weird

* Systems of Magic

** Minor Magics

*** Runecast
The Runecast are warriors that pursue the study of the ancient written language of the titans. By etching these runic symbols into their weapons and armor, they are able to augment their combat ability.

*** Spirit Caller
Spirit Callers hold a spiritual bond with the titans. In death, the titans retain the ability to influence the world through the desires of those who can call to them.

*** Harvester
Harvesters utilize the remains of titans to extract power from the carcasses of monsters twisting them to their own purposes.

** Major Magics

*** Ancient Whisperer
The Ancient Whisperers have studied the spoken language of the titans. Through great mental exertion, they can recall the forgotten language of the titans shaping the world as the titans once did.

*** Elementalist
Elementalists draw from the latent magic left behind the construction of the world.

** Other Magics

*** Weird
Some phenomenon are without explanation. Whatever was there to wind the clock of time for the first time, indifferent to the world that was set in motion, can sometimes leave its traces on the world's denizens. It's unknown why this happens, but the effect are striking.

* Equipment Classes

** Weapon Classes

*** Simple weapons

*** Heavy weapons

*** Advanced weapons

*** Ranged weapons

** Armor Classes
