#+Title: Titan Mage GM Guide
#+HTML_LINK_HOME: dummy value
#+OPTIONS: toc:t toc:2

* Being A Game Master

Every game needs a game master (GM). The game master is the arbiter of rules, the source of the game's content, and is someone that every player should be grateful for. More so than the player's the GM gets gets to flex their creativity and have the greatest involvement in the flow and feel of the game. If your game is missing a GM, then don't be afraid to try it out!

* About This Document

If you are unfamiliar with the game as a whole, reading through the Player's handbook is important for being a GM. It is recommended to start there, then come back.

Unlike the Player's Handbook, which is filled with hard rules, this document is meant to be more a process flow. If the Player's Handbook was a fish dinner, then this is the guide to fishing.

* Preparing a Session

The reality of being a GM is having to do some more legwork outside of the game than the players do. While this work can be fun on its own, the real payoff is bringing people together and seeing them engage with your world.

Preparing for a game is done at different scales, namely encounter building, adventure building, and world building. Not all of these levels need to be worked on between game sessions, so it is important to understand how to give priority to these.

The preparation that every session does need is encounters. You will almost always prepare encounters between sessions.

Above encounter building is adventure building. Adventures can last a single session or stretch out many sessions, so adventure should be prepared as you expect the current adventure to wrap up.

World building is the preparation that happens above adventure preparation. It can be some of the most creative work you get to do as a GM. Some early world building can last many adventures, so it is only needed at the beginning of the game or during big changes in the story. However, it can be fun to add to whenever the urge strikes.

** Encounter Building

Encounter building is the meat and potatoes of GM preparation. Encounters are the problems that you are going to stick in front of your players for them to figure out. The majority of game time will be spent handling the encounters, so they will actually have the biggest impact on your game.

Creating balanced encounters is a form of art. Different players will handle encounters differently and the dice can always throw a wrench into their plans. Creating challenging but rewarding encounters is a skill that can truly only come with experience with your particular players.

A cool thing to note about encounters is that it up to the players to solve them, not you. You do not always have to know how the players are going to overcome your predicaments as long as you believe that they can. Maintaining an open mind about how to solve your encounters is an important part of being a DM. Be ready to accept the solutions they propose to you, through the filter of [[* Resolving Uncertainty][unceartainty resolution]] of course!

*** Selecting Baddies

Titan Mage is an RPG about fighting monsters. Combat is a core and expected part of the game, so making sure that adventures are filled with foul fiends is a must.

Use the Foe Reference page to select some enemies for your players. Foes are categorized by the relative level your players are at: apprentice, journeyman, master, and grandmaster. It is not recommended to put higher level foes against lower level players.

Beyond the difficulty level of individual monsters, there are two other ways to balance enemies. You can add multiple monsters to the encounter. This has a multiplicative effect on the difficulty of the encounter. Be careful not to make an encounter with too many characters that bring down a player character in little time by focusing attacks. The second way to balance is in the number of encounters. Characters have a specific amount of healing that can be done before they are forced to retreat back to the safety of town. If they get worn down too much, even easy encounters can be dangerous.

As a DM, it is your job to keep a pulse on the overall health of the party. Tweaking encounter enemy numbers and the number of combat encounters should be done in order to maintain difficulty without killing the entire party.

Difficult encounters can result in player deaths. Games where players are dying constantly are not fun for the players, so it's important to manage this occurrence. Do the best job you can saving the most difficult encounters for dramatic parts in the story, so that deaths can be meaningful for the players and the other members of the party. It's possible for the death of the entire party to be their fault, but it is nearly always a failure on the GM's part.

*** Confounding Puzzles

Puzzles are a type of encounter that forces the players to think together and slows the pace of the game.

When designing puzzles that are required for adventure progression, it is important to prepare clues to feed your players when they get stuck. You can put these behind ability checks to disguise them.

Puzzles that are not required for adventure progression can be used to deliver extra rare loot or make other parts of the adventure easier. These do not need clues, but should have hints that show that the puzzle exists.

Some types of puzzles that you may with to come up with:
- Riddle: Classic spoken puzzles
- Object: Interactions with physical objects
- Social: Having to gain somebodies trust
- Cipher: Understanding hidden information
- Rube Golberg: Puzzles with multiple steps that each chain together
- Memory: Requiring players to remember information that was given a while ago

*** Dangerous Traps

*** Dolling out Treasure

*** Mapping a Dungeon

*** Other Types of Encounters

** Adventure Building

*** Hooks

*** NPCs

*** BBEG

*** Travel

*** Downtime

** World Building

*** Mapping the World

*** Creating Towns

*** Describing the World

* Running the Game

This section describes how the minutiae of the actual in person session. This is where you get to bask in the glory of the fruits of your preparation labor.

** The Core Game Loop

** Resolving Uncertainty

* Tables

** Player Stats by Level

This table shows the minimum and maximum stats that a player can have at each level.

| Level | Min HP/MP | Max HP/MP | Max Stat | Max Stat / 2 | Max Stat / 4 |
|-------+-----------+-----------+----------+--------------+--------------|
|     1 |        20 |        21 |        1 |            1 |            1 |
|     2 |        25 |        27 |        2 |            1 |            1 |
|     3 |        30 |        33 |        3 |            2 |            1 |
|     4 |        35 |        39 |        4 |            2 |            1 |
|     5 |        40 |        50 |        5 |            3 |            2 |
|     6 |        45 |        57 |        6 |            3 |            2 |
|     7 |        50 |        64 |        7 |            4 |            2 |
|     8 |        55 |        71 |        8 |            4 |            2 |
|     9 |        60 |        87 |        9 |            5 |            3 |
|    10 |        65 |        95 |       10 |            5 |            3 |
|    11 |        70 |       103 |       11 |            6 |            3 |
|    12 |        75 |       111 |       12 |            6 |            3 |
|    13 |        80 |       132 |       13 |            7 |            4 |
|    14 |        85 |       141 |       14 |            7 |            4 |
|    15 |        90 |       150 |       15 |            8 |            4 |
|    16 |        95 |       159 |       16 |            8 |            4 |

* Homebrew Content

If you find that the options in the game are too limiting or wish to add something specific to your game, here are some references that can help with the design. 

** Creating Spells

Spellmaking is not an exact science, but there are some guidelines. In general, spells should not cost more than 40 MP.

For damage dealing spells, a spell should cost MP equal to the average amount of damage it deals. If the spell hits two to three targets, its cost should be doubled. If it hits more than that, its cost should be tripled. The cost should be adjusted based on how difficult it is to hit. The following table lists recommended level requirements for damage dealing spells.

| Character Rank    | Total Average Damage |
|-------------------+----------------------|
| Apprentice (1-5)  |                 0-10 |
| Journeyman (6-10) |                10-20 |
| Master (11-15)    |                20-30 |
| Grandmaster (16)  |                30-40 |

For utility spells costs, use the following table.

| Utility Benefit  | MP Cost |
|------------------+---------|
| Situational      |       5 |
| Good             |      10 |
| Great            |      20 |
| Amazing          |      40 |
| Earth Shattering |      80 |

-----

#+begin_cw
Game on
#+end_cw
