#+Title: Titan Mage GM Guide
#+HTML_LINK_HOME: dummy value
#+OPTIONS: toc:t toc:2

* Being A Game Master

Every game needs a game master (GM). The game master is the arbiter of rules, the source of the game's content, and is someone that every player should be grateful for. More so than the players the GM gets gets to flex their creativity and have the greatest involvement in the flow and feel of the game. If your game is missing a GM, then don't be afraid to try it out!

* About This Document

If you are unfamiliar with the game as a whole, reading through the Player's handbook is important for being a GM. It is recommended to start there, then come back.

Unlike the Player's Handbook, which is filled with hard rules, this document is meant to be more a process flow. If the Player's Handbook was a fish dinner, then this is the guide to fishing.

* Preparing a Session

The reality of being a GM is having to do some more legwork outside of the game than the players do. While this work can be fun on its own, the real payoff is bringing people together and seeing them engage with your world.

Preparing for a game is done at different scales, namely encounter building, adventure building, and world building. Not all of these levels need to be worked on between game sessions, so it is important to understand how to give priority to these.

The preparation that every session does need is encounters. You will almost always prepare encounters between sessions.

Above encounter building is adventure building. Adventures can last a single session or stretch out many sessions, so adventure should be prepared as you expect the current adventure to wrap up.

World building is the preparation that happens above adventure preparation. It can be some of the most creative work you get to do as a GM. Some early world building can last many adventures, so it is only needed at the beginning of the game or during big changes in the story. However, it can be fun to add to whenever the urge strikes.

** Encounter Building

Encounter building is the meat and potatoes of GM preparation. Encounters are the problems that you are going to stick in front of your players for them to figure out. The majority of game time will be spent handling the encounters, so they will actually have the biggest impact on your game.

Creating balanced encounters is a form of art. Different players will handle encounters differently and the dice can always throw a wrench into their plans. Creating challenging but rewarding encounters is a skill that can truly only come with experience with your particular players.

A cool thing to note about encounters is that it up to the players to solve them, not you. You do not always have to know how the players are going to overcome your predicaments as long as you believe that they can. Maintaining an open mind about how to solve your encounters is an important part of being a DM. Be ready to accept the solutions they propose to you, through the filter of [[* Resolving Uncertainty][unceartainty resolution]] of course!

Before you begin planning out your encounters, you should have a theme in mind from your [[* Adventure Building][adventure building]]. Keep that theme in mind when choosing which encounters to include.

*** Selecting Baddies

Titan Mage is an RPG about fighting monsters. Combat is a core and expected part of the game, so making sure that adventures are filled with foul fiends is a must.

Use the Foe Reference page to select some enemies for your players. Foes are categorized by the relative level your players are at: apprentice, journeyman, master, and grandmaster. It is not recommended to put higher level foes against lower level players.

Beyond the difficulty level of individual monsters, there are two other ways to balance enemies. You can add multiple monsters to the encounter. This has a multiplicative effect on the difficulty of the encounter. Be careful not to make an encounter with too many characters that bring down a player character in little time by focusing attacks. The second way to balance is in the number of encounters. Characters have a specific amount of healing that can be done before they are forced to retreat back to the safety of town. If they get worn down too much, even easy encounters can be dangerous.

As a DM, it is your job to keep a pulse on the overall health of the party. Tweaking encounter enemy numbers and the number of combat encounters should be done in order to maintain difficulty without killing the entire party.

Difficult encounters can result in player deaths. Games where players are dying constantly are not fun for the players, so it's important to manage this occurrence. Do the best job you can saving the most difficult encounters for dramatic parts in the story, so that deaths can be meaningful for the players and the other members of the party. It's possible for the death of the entire party to be their fault, but there is almost always a way that GMs can massage the difficulty of an adventure without breaking the rules of the game.

*** Confounding Puzzles

Puzzles are a type of encounter that forces the players to think together and slows the pace of the game.

When designing puzzles that are required for adventure progression, it is important to prepare clues to feed your players when they get stuck. You can put these behind ability checks to disguise them.

Puzzles that are not required for adventure progression can be used to deliver extra rare loot or make other parts of the adventure easier. These do not need clues, but should have hints that show that the puzzle exists.

Some types of puzzles that you may with to come up with:
- Riddle: Classic spoken puzzles
- Object: Interactions with physical objects
- Social: Having to gain somebodies trust
- Cipher: Understanding hidden information
- Rube Golberg: Puzzles with multiple steps that each chain together
- Memory: Requiring players to remember information that was given a while ago
- Time: Can only be solved at a specific time of day/season/etc.
- Layout: Rooms that shift changing the path to get somewhere

*** Dangerous Traps

Traps are a source of danger other than combat encounters. Traps can be a source of damage, but there are many insidious ways for traps to work:
- Damage: Straightforward traps that deal damage
- Effect: Traps that inflict negative conditions
- Enclosures: Locking players into a specific room or area
- Party Splitter: Traps that keep players away from each other
- Sound: Alerts enemies in the area
- Timer: Areas that get progressively more dangerous over time

It is up to you how the trap is triggered. Whether it is automatic or whether an enemy has to set it off. It is also up to you if the traps can be disabled or not.

*** Dolling out Treasure

Players love treasure, and they will love you for giving them cool treasure. It's a psychology thing.

There are three main types of treasures:
- Shells: Raw currency
- Valuables: Items that can be traded for raw currency
- Artifacts: Equipment that is marked epic or legendary

Shells are a straightforward treasure. Players need it to buy equipment, live in town, and level up.

Valuables are essentially another way to give out shells, but they have a few advantages. First, valuables can be kept by foes who normally wouldn't carry shells. They can be crafted to fit the theme of the other adventure encounters. Finally they can serve to add realism to the world when the players inevitably to trade them for shells. Some merchants might buy certain values at a higher price or have plot hooks for the player concerning specific valuables.

Artifacts are the last kind of treasure. Artifacts are a way separate from character level to increase the ability of the party. Within the Player's resource tables are items marked as epic or legendary. These are the artifacts. Artifacts can not be typically bought or sold, so instead they should be given out as adventure rewards or as hidden treasure.

When deciding how many shells or valuables to put into an adventure, use the character level table from the Player's Handbook to decide. It's up to you to set a pace for how often the player's can level up, but in giving out enough treasure for one level per adventure is a good pace.

It's recommended to give out artifacts roughly based on the player character ranks from the character level table. Apprentice players should acquire a couple minor epic artifacts. Consumables or equipment are good candidates. Journeyman should begin to get a couple of the rarer combat focused artifacts or ones with strong effects. Still only epic level though. A master should receive a legendary artifact and continue to receive epic artifacts. Once a player reaches grandmaster level, artifacts are the only way to continue increasing their power, so if you wish to keep the campaign going you are allowed to be more liberal.

*** Mapping a Dungeon

At this point in your adventure prep, you should have some assortment of baddies, puzzles, traps, and treasure. It is at this point that you should design the map.

Some adventure may take place out in the open, and in that case, there's not much of a map to plan, but if your player's are delving into a dungeon, cave, building, ship or other enclosed space, it's good to create some interconnected rooms to fill with all of your encounters. Doing the mapping after the other encounter preparation will help tell you how big of an area to map out.

There are many ways to lay out a map. The simplest is just a linear set of rooms with one encounter after another. That is a fine way to do it. At it's biggest, a map can have multiple entrances, large paths of dead ends, and enough rooms to last multiple adventures. Most maps will fall somewhere in the middle. The best way do design a map of course is to follow your heart, and figure out through experimentation what types of maps are good for you and your players.

** Adventure Building

Adventures are the containers for your encounters. They set the theme, the pace, and the difficulty. A good juicy adventure preparation will convince the players and their characters that experiencing dangers will be worth it.

*** Crafting an Adventure

Adventures come in many shapes and sizes. Your first adventure should be small. Perhaps to help deliver a parcel through a dangerous road. As characters level up, the risks and bounties of adventures can grow. Because players are only able to fully recover while in a town, it's important for adventures to be scoped to the players level and items.

If needed adventures can be nested, so that players complete objectives that lead toward a larger goal.

Making a new adventure out of the blue is always an option, but forming an adventure from information that you've already given to the players by intentionally splipping in some future information or using a [[* Creating Towns][town happening]] can help keep up the continuity of your world.

Here are ideas for some adventure goals that you may want to use:
- Hired Sword: Hiring to clear out some local monsters
- Retrieval: Delving to bring back an item or people of importance
- Delivery: Sending an object or people safely between areas
- Mystery: Uncovering secret information or a hidden object
- Negotiation: Being a mediator for two large parties
- Escape: Getting out of a dire situation
- Happenstance: Curious characters may be interested in unexpected events or structures for the sake of exploring

*** Hooks

Hooks are the scenes where you try and convince the players that you adventure needs to happen. Hooks can be as subtle as mentioning a mysterios stranger at a bar or as straightforward as telling your players that they have become lost in a dense fog. The goal of the hook is to convince the players, so here are some reasons that players may be interested:
- Rewards: [[* Dolling out Treasure][Money, valuables, and rare items]]
- Morals: Helping the less fortunate or opressed
- Relationships: If an [[* NPCs][NPC]] that the players know or a family member of the characters requests help
- Exploration: Seeing some cool new area or environment
- Furthering Goals: If the results of this adventure help the players complete a larger goal or adventure
- Good Players: A good player is aware that they that you have done the work to set up an adventure and will have an eye out for your clues
- Mandatory Fun: As a last resort, you can use the power of GM handwoven narration to begin an adventure, best used as a last resort

When you are not sure what kind of hook to make, take a look at your players' motivations for inspiration.

*** Travel

When adventuring invitably takes the party further away on the [[* Mapping the World][map]], it's time to do some travel resolution. It's up to the players to let you know what path they are going to take and what speed they are going to travel at. Based on their speed, this is how many hexes can be covered in a day of traveling:
- Fast: (3mph) 4 hexes per 8 hour travel time
- Slow: (2mph) 3 hexes per 8 hours travel time
  
You may with to introduce to planned or random encounters while traveling. Here are some considerations that can help when deciding what to plan:
- Distance: The total distance traveled
- Terrain: Is the party traveling on a road or through a dangerous forest
- Speed: Fast vs slow
- Location: Is this path close to civilization or to any baddie encampments
- Party State: Will another encounter wipe the entire party after a tense adventure
  
Road encounters need not always be combat. Meeting people along the road or neutral creatures in the wild can help show how the different areas in your world are laid out.

*** Downtime

Eventually players will want to return back to town. They need to recover, sell valuables, level up, and prepare for the next adventure. Ask your players how long they are planning to stay in town and what downtime actions they are gong to take.

It is up to you whether to resolve these actions through quick narration or whether you want to play out the scenarios. Playing then out can help build rapport with [[* NPCs][NPCs]], to give out details about [[* Creating Towns][town happenings]], or to provide your next [[* Hooks][hook]].

** World Building

*** NPCs

*** Mapping the World

*** Creating Towns

*** Describing the World

* Running the Game

This section describes how the minutiae of the actual in person session. This is where you get to bask in the glory of the fruits of your preparation labor.

** The Core Game Loop

** Resolving Uncertainty

* Tables

** Player Stats by Level

This table shows the minimum and maximum stats that a player can have at each level.

| Level | Min HP/MP | Max HP/MP | Max Stat | Max Stat / 2 | Max Stat / 4 |
|-------+-----------+-----------+----------+--------------+--------------|
|     1 |        20 |        21 |        1 |            1 |            1 |
|     2 |        25 |        27 |        2 |            1 |            1 |
|     3 |        30 |        33 |        3 |            2 |            1 |
|     4 |        35 |        39 |        4 |            2 |            1 |
|     5 |        40 |        50 |        5 |            3 |            2 |
|     6 |        45 |        57 |        6 |            3 |            2 |
|     7 |        50 |        64 |        7 |            4 |            2 |
|     8 |        55 |        71 |        8 |            4 |            2 |
|     9 |        60 |        87 |        9 |            5 |            3 |
|    10 |        65 |        95 |       10 |            5 |            3 |
|    11 |        70 |       103 |       11 |            6 |            3 |
|    12 |        75 |       111 |       12 |            6 |            3 |
|    13 |        80 |       132 |       13 |            7 |            4 |
|    14 |        85 |       141 |       14 |            7 |            4 |
|    15 |        90 |       150 |       15 |            8 |            4 |
|    16 |        95 |       159 |       16 |            8 |            4 |

* Homebrew Content

If you find that the options in the game are too limiting or wish to add something specific to your game, here are some references that can help with the design.

** Creating Spells

Spellmaking is not an exact science, but there are some guidelines. In general, spells should not cost more than 40 MP.

For damage dealing spells, a spell should cost MP equal to the average amount of damage it deals. If the spell hits two to three targets, its cost should be doubled. If it hits more than that, its cost should be tripled. The cost should be adjusted based on how difficult it is to hit. The following table lists recommended level requirements for damage dealing spells.

| Character Rank    | Total Average Damage |
|-------------------+----------------------|
| Apprentice (1-5)  |                 0-10 |
| Journeyman (6-10) |                10-20 |
| Master (11-15)    |                20-30 |
| Grandmaster (16)  |                30-40 |

For utility spells costs, use the following table.

| Utility Benefit  | MP Cost |
|------------------+---------|
| Situational      |       5 |
| Good             |      10 |
| Great            |      20 |
| Amazing          |      40 |
| Earth Shattering |      80 |

-----

#+begin_cw
Game on
#+end_cw
