#+Title: Titan Mage Player's Handbook
#+HTML_LINK_HOME: dummy value
#+OPTIONS: toc:t toc:2

* Introduction

** The World of Titan Mage

The world of Titan Mage began with the titans. The colossal beings used might and magic to shear the plains flat, heat the core of the planet, and gift the world with water and sun. Today, their fossilized remains are strewn about the world in hidden groves. Nobody knows how they came to die, but legend says that they gave up their power willingly, to share their earthen canvas with the rest of life's creatures.

Without the chaos of the titan's ongoing construction, the creatures of the world were allowed to grow and evolve. With enough time, the lands became overgrown with all manner of beast. Intelligence alone was not enough to live at the top of the food chain, so lowly humans were relegated to hiding and building what defenses they could, praying that their independent settlements not fall victim to ruin.

But the world is beginning to change once again. Humans are uncovering the magic that the titans left behind. With this newfound power, they are striking out, exploring the world, and trading with others for the first time. It is in this setting that Titan Mage takes place. There is high demand for those who can defend against the wilds. The best adventurers of the world are renowned and exalted, but not many of them are very wrinkled...

** What is Needed to Play

Titan Mage is meant to be played with two or more players. The sweet spot is 3 to 5 players and another player be the Game Master, abbreviated GM from here on out.

Each player requires one full set of RPG dice: a four sided die (d4), a six sided die (d6), a ten sided die (d10), a twelve sided die (d12), a twenty sided die (d20), and a ten sided die with multiples of 10 (used with the d10 to make a d100).

It is recommended to have two sets per player so that multi-dice rolls can occur at once.

Any die with a zero side is used as the max value for the die. For example, the zero on a d10 has a value of 10.

** Creating a Character

Use the following checklist to create a new character.

- Download a new character sheet
- Decide on a [[* Player Classes][player class]]
  - Fill in the class name
- Assign [[* The Main Stats][main stats]]
  - Fill in the main stats in any order with the numbers 1, 1, 0, 0
- Decide on a [[* Systems of Magic][magic system]] compatible with your player class
  - Fill in the magic system name
  - Fill in your starting spell choices
- Formulate a [[* Backstory][backstory]]
- Fill in your character name

** Conventions

This section lists some conventions used in Titan Mage.

- *Rounding*: Any time rounding is required, always round up.
- *Dice Markings*: Damage values are usually marked with die to roll, d6, d10, etc. If multiple dice of the same type are to be rolled, the dice value will be prefixed with a number. For example 4d6 means to roll 4 d6 dice and add the value of all the rolls together. Some dice rolls are marked with a tilde and parentheses ~(2d4). For these rolls, roll 2 dice and subtract the larger value from the smaller. This may use dice of different size, e.g. ~(d4,d6). Always subtract the larger rolled value, regardless of which die has more sides.

* Character Stats

** Character Level

The level of your character is a measure of how skilled they are at their craft. This skill is manifested in additional stats, features, and magical ability.

Character level starts at 1 and goes up to 16. In order to level up, characters need to both gain experience out adventuring and spend time and money in [[* Towns][town]]. Your DM will let you know when you have gained enough experience to advance in level, but it is up to you to choose when to spend the time and money to learn the next level during [[* Town Actions][your town actions]].

At the 6th level, a study under a master is required. Masters are not uncommon, but are not found in every town. At the 11th level, a study under a grandmaster is required. Although most grandmasters are well known in story and legend, not all of them can be easy to find. In order to attain the 16th level, one has to advance their field beyond it's current limits. Work with your DM to discuss your plan for this, as such things do not come with a one size fits all price tag.

Use the following requirements chart to see what it takes to make it to level up. The monetary price to level up does not include [[* Living Expenses][living expenses]].

#+begin_xtable
| Level | Location          | Time     | Monetary Cost | Rank           |
|-------+-------------------+----------+---------------+----------------|
|     1 | N/A               | N/A      | N/A           | Apprentice     |
|     2 | Adventure Hall    | 1 month  | 100 Shells    | Apprentice II  |
|     3 | Adventure Hall    | 1 month  | 200 Shells    | Apprentice III |
|     4 | Adventure Hall    | 1 month  | 300 Shells    | Apprentice IV  |
|     5 | Adventure Hall    | 1 month  | 400 Shells    | Apprentice V   |
|     6 | Master Study      | 6 months | 1000 Shells   | Journeyman     |
|     7 | Adventure Hall    | 2 months | 1200 Shells   | Journeyman II  |
|     8 | Adventure Hall    | 2 months | 1400 Shells   | Journeyman III |
|     9 | Adventure Hall    | 2 months | 1600 Shells   | Journeyman IV  |
|    10 | Adventure Hall    | 2 months | 1800 Shells   | Journeyman V   |
|    11 | Grandmaster Study | 1 year   | 3000 Shells   | Master         |
|    12 | Adventure Hall    | 3 months | 3500 Shells   | Master II      |
|    13 | Adventure Hall    | 3 months | 4000 Shells   | Master III     |
|    14 | Adventure Hall    | 3 months | 4500 Shells   | Master IV      |
|    15 | Adventure Hall    | 3 months | 5000 Shells   | Master V       |
|    16 | ?                 | ?        | ?             | Grandmaster    |
#+end_xtable

Whenever you level up, perform the following actions:

- Add five to your [[* Health Points (HP)][HP]] and [[* Magic Power (MP)][MP]]
- Increase two different [[* The Main Stats][main stats]] by one point
- Recalculate [[* Auxiliary Stats][aux stats]] as needed

** The Main Stats

Main stats directly measure character prowess. They influence other stats and are used for determining outcomes in [[* Ability Check][ability checks]].

These stats range from 1 to 21. When stats are upgraded, the effects of stats are always retroactive.

Stats are often to modify the damage of attacks or spells as either + stat, + stat/2, or + stat/4. Use the following table to reference these values.

| Stat | Stat/2 | Stat/4 |
|------+--------+--------|
|    0 |      0 |      0 |
|    1 |      1 |      1 |
|    2 |      1 |      1 |
|    3 |      2 |      1 |
|    4 |      2 |      1 |
|    5 |      3 |      2 |
|    6 |      3 |      2 |
|    7 |      4 |      2 |
|    8 |      4 |      2 |
|    9 |      5 |      3 |
|   10 |      5 |      3 |
|   11 |      6 |      3 |
|   12 |      6 |      3 |
|   13 |      7 |      4 |
|   14 |      7 |      4 |
|   15 |      8 |      4 |
|   16 |      8 |      4 |
|   17 |      9 |      5 |
|   18 |      9 |      5 |
|   19 |      9 |      5 |
|   20 |      9 |      5 |
|   21 |     10 |      6 |

There are four main stats.

*** Power

/Power is used to express physical strength. Cleave, crush, and grapple your way through enemies./

Direct Effects:

- Extra [[* Health Points (HP)][HP]] per level: Power / 4

Other Effects:

- Extra damage with traditional weapons

*** Reflex

/Reflex measures your speed and reaction. Evade dangers and act before others. A high reflex shoots first./

Direct Effects:

- Combat order: Higher reflex acts first
- Modified defense threshold: [[* Defense Threshold][Defense threshold]] reduced by Reflex / 4

Other Effects:

- Extra damage with specialized weapons

*** Focus

/Focus allows you to concentrate and understand complex concepts. Perceive the dangers around you and outwit opponents./

Direct Effects:

- Extra MP per level: Focus / 4
- Extra [[* Systems of Magic][learned spells]]: Focus / 4

Other Effects:

- Able to learn more powerful spells

*** Presence

/A high presence signifies awareness of the world around you. Anticipate the actions of others and make them pay for their predictability./

Direct Effects:

- [[* Damage Types][Physical damage]] critical strike chance: D20 roll <= Presence

Other Effects:

- Extra spell damage

** Auxiliary Stats

*** Health Points (HP)

Health points tracks the life of your character. At 0 HP, your character becomes [[* Incapacitated][incapacitated]]. Characters gain extra health at every level based on their [[* Player Classes][class]].

*** Magic Power (MP)

Magic power tracks the amount of magic that a character can perform. Characters gain extra magic power at every level based on their [[* Player Classes][class]].

*** Defense

Defense provides flat physical damage reduction. Defense is provided primarily by your [[* Combat Equipment][armor]]. Certain abilities are able to reduce an opponents defense and are marked as /armor piercing/.

*** Defense Threshold

The reduction in damage provided by [[* Defense][defense]] only goes into effect after a certain ammount of damage is taken. This ammount is the damage threshold. Damage threshold is set by your [[* Combat Equipment][armor]] and is reduced by [[* Reflex][reflex]] and by equipping shields.

As an example, say you have 3 defense and 5 damage threshold. If you take 7 damage, your defense kicks in after 5 damage, leaving 2 damage that is affected by defense. 3 is greater than two, so both points of damage are reduced and you take 5 damage.

*** Magic Resistance

Magic resistance provides flat magic damage reduction. Magic resistance is rare, and is not provided by any normal armors. There is no magic resistance threshold, the reduction is always applied.

*** Movement Speed

Movement speed is a measure how fast your character is. In [[* Combat][combat]], your character is allowed to move up to their movement speed in squares every round.

When moving diagonal, treat the first diagonal move as one square of movement, the second diagonal move as two squares of movement, then one, then two, etc.

* Combat

In combat, players and enemies take turns performing actions. A turn is broken up into one major action, one minor action, and as many as needed free actions. One is always free to use a minor action in place of a major action.

** Turn Order

Turn order is decided by the [[* Reflex][reflex]] stat. A higher stat means you go first. Ties are decided by the players.

** Default Major Actions

*** Weapon Attack

Characters make an attack against an enemy using an equipped weapon. An unarmed attack can be made for 1 damage if no weapons are equipped.

Whenever a weapon attack that inflicts [[* Damage Types][physical damage]] is made, roll a d20. If your roll [[* Presence][presence]] stat is equal or higher than the roll, double the damage of the attack.

*** Spell Cast

Characters who are learned in a [[* Systems of Magic][school of magic]] that provides spells marked as a major action can cast them.

*** Guard

Characters have their [[* Defense Threshold][defense threshold]] set to 0 until the beginning of their next turn.

** Default Minor Actions

*** Movement

Characters move up to their [[* Movement Speed][movement speed]].

*** Swapping Held Items

Characters put away, replace, or take out items that can be used when held.

*** Offhand Weapon Attack

Characters with two one handed weapons can attack with the off hand as a minor action. Offhand weapon damage ignores any scaling from [[* Character Stats][stats]] and only deals damage from the dice rolls. In addition offhand attacks cannot crit.

*** Reloading

Characters load ammunition into a ranged weapon, a bow for example.

** Damage Types

Damage dealt by weapons is counted as physical damage and can be reduced by the [[* Defense][defense]] stat (after [[* Defense Threshold][defense threshold]] is calculated in). When making a physical damage attack, make sure to roll a d20 to check for [[* Presence][crits]].

Damage dealt by spells is counted as magical damage and can be reduced by the [[* Magic Resistance][magic resistance]] stat. Attacks made with magical damage can not crit.

** Conditions

*** Blinded

A blinded character can only make attacks against the last enemy that took their turn. Creatures with other heightened senses may not be affected by blindness.

*** Chilled

When chilled, you may only take a [[* Default Major Actions][major action]] on your turn.

*** Exhausted

Characters who are exhausted cannot take major actions and their [[* Movement Speed][movement speed]] is reduced by half.

*** Fallen

In the fallen condition, you are unable to make the [[* Weapon Attack][weapon attack]] major action or the [[* Movement][movement]] minor action. Standing back up takes a major action. While fallen, instead of the normal movement minor action, you can use a minor action to roll one square.

*** Incapacitated

When a player drops below 0 HP, they become incapacitated. They are unable to take major or minor actions or regain HP normally.

Upon entering the state, they make a power [[* Ability Check][ability check]] (12). On a successful check, the character returns to 0 HP, and the effect ends at the end of the current fight. On a failed check, the character stays incapacitated until [[* Recovering][recovery]], and the character becomes afflicted by a [[* Grievous Wound][grievous wound]].

The condition can also be ended by a spell or item that provides the revive affect, returning the character to 1 HP and ending the effect, even during battle.

Every time a character is attacked while incapacitated, they suffer another [[* Grievous Wound][grievous wound]]. Some foes may ignore downed combatants, but not all are so merciful.

*** Paralyzed

A paralyzed character is unable to take any action. Their [[* Defense Threshold][defense threshold]] is doubled while paralyzed.

*** Death

Death is the end of your playable character. They have succumbed to their injuries and pass on to the final rest.

This is a good chance to say some final words to your comrades.

** Grievous Wound

When a character sustains critical injury, they become afflicted by a grievous wound. Roll a d6 to determine your characters grievous wound. This wounds cannot be removed by normal healing. If any grievous wound, except for Lucky Save, is rolled two times, then the character suffers [[* Death][death]].

*(1) Lucky Save*

Your character sees life flash before their eyes, but fortune favors the lucky. No negative effects are experienced.

*(2) Head Trauma*

The character is unable to remember people and motivations from their past. They must invent a new false backstory or find a new purpose.

*(3) Gnarly Scars*

The many wounds gained over time have accumulated and worn down the player. Their maximum [[* Health Points (HP)][HP]] is halved.

*(4) Damaged Arm*

Damage to one arm becomes too severe to save. Your character is no longer able to wield two handed equipment and can only wield one one handed equipment.

*(5) Damaged Leg*

Bone injuries have left the player with a worn gait. Their base [[* Movement Speed][movement speed]] is halved.

*(6) Death*

The character experiences [[* Death][death]].

** Recovering

Recovering is the process of regaining HP and MP. Certain classes regain additional resources while recovering.

*** Respite

A respite is the only recovery that can occur while out adventuring. A respite requires an uninterrupted rest of at least 4 hours. Spending 8 or more hours resting does not increase the resources gained, and a respite can only occur once a day.

After a respite, each player rolls a d6 up to their character level number of times. The players choose whether to add the value on the die rolled to their [[* Health Points (HP)][HP]] or [[* Magic Power (MP)][MP]].

Once character level number of respite dice have been rolled, no more can be rolled until a full recovery has occurred.

Respite can be modified by certain [[* Player Classes][classes]] and [[* Systems of Magic][magic systems]].

*** Full Recovery

A full recovery restores all of a character's [[* Health Points (HP)][HP]] and [[* Magic Power (MP)][MP]], but can only occur in [[* Towns][town]] over the period of a week. A full recovery will reset the number of respite dice rolled back to zero.

* Roleplaying

** Skills

Skills are trades that can be learned while in [[* Towns][town]] in order to augment a character's abilities. Skills take three months of time to learn and have an upfront cost. A character can learn a maximum of three skills.

*** Alchemy

The alchemy skill allows you to identify potions on your own. In addition, you can craft a simple potion during a [[* Respite][respite]].

Alchemy requires 1,000 shells to learn.

*** Appraisal

Appraisal lets you to better determine the value of rare items like gems, idols, and the like.

Appraisal requires 500 shells to learn.

*** Horseback Riding

Horseback riding allows you to ride trained horses.

Horseback riding requires 300 shells to learn.

*** Lockpicking

Lockpicking allow you to attempt to pick locks.

Lockpicking requires 2,000 shells to learn.

*** Smithing

The smithing skill helps you to determine the value of weapons that you come across. In addition, you can craft common weapons while in [[* Town Actions][town]].

Smithing requires 1,000 shells to learn.

** Ability Check

Ability checks are a way to use dice in combination with player stats to resolve an outcome.

The DM will ask for an ability check of a player for a particular [[* The Main Stats][main stat]]. It's the players job to roll a d12 and add their stat to the roll. It will then be up to the DM to resolve outcome.

** Dialog

Speaking with Non-Player Characters (NPCs) is a common part of adventuring. Players may wish to elicit information from a knowledgeable town resident, haggle on the price of a rare artifact, or convince an animal that they are friendly.

When players are expecting a result out of their conversation, it's the job of the DM to recognize this and ask for an [[* Ability Check][ability check]]. Players have many ways to be convincing, and the strength of their argument can have a great affect on the difficulty of the ability check.

Dialog is also one of the best ways to show off your character's personality!

** Backstory

Your character's backstory describes why they have just become an adventurer. It can be as short as, "I vow to buy back my family's farm from the evil baron", or as long as you enjoy writing it.

An important point to keep in mind is that your character is just starting out. Every character is capable of great deeds, but you get to discover them through playing the game, not crafting a backstory. Discovering who your character is by playing is one of the pleasures of TTRPGs.

* Towns

Towns provide a safe haven between adventures, a place to rest weary bones, and prepare for what's next.

** Living Expenses

Every month of time spent in town incurs living expenses. The price of these expenses depends upon your desired station. It may be tempting to choose meager living expenses, but know that you station effects how others perceive you. The rarest [[* Artifacts][artifacts]] and most lucrative jobs often go to those of high station. The prices for living expenses are shown in the following table.

#+begin_xtable
| Station | Monthly Expenses |
|---------+------------------|
| Meager  | 50 Shells        |
| Frugal  | 100 Shells       |
| Average | 200 Shells       |
| High    | 500 Shells       |
| Royal   | 1000 Shells      |
#+end_xtable

** Town Features

Towns support people from many walks of life. While in town you may wish to make use of services provided there. Not every town provides all of these services.

*** Adventure Hall

Adventure Halls are places where for hire adventurers can train and scout for work.

*** Apothecary

Apothecaries sell potions and droughts that may help you while you are away.

*** Bank

It's not very practical to carry around all the money and equipment that you have accumulated. Banks offer you a way to secure possessions.

*** Cartographer

Cartographers are designers of maps. The more expensive ones are typically the more accurate.

*** Cobbler

Cobblers sell and repair footwear.

*** General Store

General Stores sell simple craft and imported goods.

*** Library

Libraries are rare and are usually tied to universities.

*** Market

Markets are areas, typically outdoors, where foods and crafts are sold.

*** Smithy

Smithies sell metal forged tools.

*** Stable

Stables house pack animals for a price. Some stables offer animals for sale.

*** Tailor

Tailors sell garments of various quality.

** Town Actions

You may be returning to town just for the sake of a [[* Full Recovery][full recovery]], but why not take advantage of what the town has to offer? Time spent in town is devoted to town actions. Town actions occur on the order of months, and each member of the party need not take the same town actions at the same time.

*** Learning Skills

Time in town can be spent learning a new [[* Skills][skill]]. See the list of skills for time and cost requirements.

*** Training

Time spent training at an [[* Adventure Hall][adventure hall]] allows you to [[* Character Level][level up]]. See the level up table for the time ranges and costs.

*** Mentorship

As your character gains levels, the ability to become a mentor assisting an unplayed character in leveling up becomes available. Players are responsible for creating a full character sheet for their mentee. A mentee must remain at least 5 levels lower than the player character.

Being a mentee takes time equal to the player character's . In exchange for your time and expertise, your character is rewarded with the price of [[* Character Level][level ups]] for the level the mentee gains.

Mentees are not able to gain levels back to back. Just like players, they need time to develop their new knowledge. This amount of time is at the DM's discretion.

Mentees may wish to join your adventuring party at such unfortunate times that room becomes available...

*** Philanthropy

Many organizations rely on the generosity of rich adventurers. You may wish to spend time donating funds or volunteering for an organization that your character is aligned with.

*** Research

Time can be spent researching a topic in town. Asking around, checking scholarly records. Some research tasks can go easier with a little grease.

*** Shopping

Adventuring requires extreme preparation. Before embarking, it is wise to stock up on items to help you while away.

*** Spellwork

By practicing you magic craft, a spell from your spell list can be swapped out.

*** Working

Taking up temporary work allows you to live with frugal [[* Living Expenses][expenses]] without costing any gold. Performing skilled labor may pay for higher expenses and the DM's discretion.

* Player Classes

** Tactician

Tacticians are able to survey a battlefield with ease. They are able to command allies, increasing their battle effectiveness, and have insight into enemies traits.

Starting [[* Health Points (HP)][HP]]: 10

Starting [[* Magic Power (MP)][MP]]: 10

At the first level, tacticians gain the *delayed action* class feature. This allows the player to take their minor action, major action, or both actions later in the turn order. The conditions for taking the turn and the action that is to be taken must be expressed during your normal turn.

At the third level, tacticians gain the *battle insight* minor action. This lets the tactician determine either the remaining [[* Health Points (HP)][HP]] of a single enemy, the current [[* Defense][defense]] of a single enemy, or the damage weaknesses of a single enemy.

At the fifth level, tacticians gain the *dual guard* major action. If an ally is within five feet of the tactician, both they and the tactician gain the effect of the guard. This can only affect one ally per turn, and that ally cannot benefit from a guard of their own on the same turn.

At the seventh level, tacticians gain the *unguard* minor action. This removes the extra [[* Defense][defense]] that an enemy gains when using the [[* Guard][guard]] action.

At the ninth level, tacticians gain the *minor shot calling* minor action. This lets another player character take a minor action during your turn instead of you. You decide who, and they decide which action to take. They cannot take the same minor action the next time they take their turn.

At the eleventh level, tacticians gain the *major shot calling* major action. This lets another player character take a major action during your turn instead of you. You decide who and they decide which major action. They cannot take the same action the next time they take their turn.

At the thirteenth level, tacticians gain the *tactical insight* class feature. Whenever battle insight is used, also learn what major and minor actions an enemy is going to use on their turn.

At the fifteenth level, tacticians gain the *battle instincts* class feature. This makes *battle insight* into a free action that can be used once per turn.

At the sixteenth level, tacticians gain the *battle commander* class feature. This combines the effects of minor shot calling and major shot calling, and turns them into a free action.

** Mercenary

Mercenaries are masters of combat and weaponry, able to wield the rarest weapons and strongest armors. Cleaving and rending is the way of the Mercenary.

Starting [[* Health Points (HP)][HP]]: 20

Starting [[* Magic Power (MP)][MP]]: 5

At the first level, mercenaries gain the *engage* minor action. This can be used when an enemy is within 1 square. Until the beginning of your next turn, if the enemy you target moves from their square, you may take a free attack action during their turn as soon as they move. This effect lasts until you or the enemy moves at least one square.

At the third level, mercenaries gain the *distracted strike* class feature. This lets allies add 10 to crit roles when targeting enemies that you have engaged. If the enemy moves away from you, this bonus no longer applies.

At the fifth level, mercenaries gain the *shove* major action. This puts a normal or smaller size enemy into the [[* Fallen][fallen]] state.

At the seventh level, mercenaries gain the *en guarde* class feature. Once per [[* Respite][respite]] when your [[* Health Points (HP)][HP]] is reduced to 0, it remains at 1 instead.

At the ninth level, mercenaries gain the *quick engage* class feature. This turns *engage* into a free action that can be used once per turn.

At the eleventh level, mercenaries gain the *power strike* minor action. When combined with the [[* Weapon Attack][weapon attack]] major action, your subtracted dice rolls become additive.

At the thirteenth level, mercenaries gain the *charge* class feature. When taking the [[* Movement][movement]] minor action, as long as your movement is a straight line. You can use *shove* as a free action if an enemy stands at the end of your charge.

At the fifteenth level, mercenaries gain the *quick draw* class feature. This lets a mercenary [[* Swapping Held Items][switch weapons]] as a free action instead of a minor action.

At the sixteenth level, mercenaries gain the *battle master* class feature. This lets you make two attacks when using the [[* Weapon Attack][weapon attack]] major action.

** Assassin

Assassins are skilled dealing damage through the use of well placed attacks and devious weapon modifications. Few can stand before an Assassin and live to tell the tale.

Starting [[* Health Points (HP)][HP]]: 15

Starting [[* Magic Power (MP)][MP]]: 10

At the third level, assassins gain the *sneaky strike* minor action. When targeting an enemy with a [[* Weapon Attack][weapon attack]] this turn, if an ally is within 1 square of the enemy you are targeting, you may reroll one of your weapon damage die when attacking that enemy.

At the third level, assassins gain the *disarm* major action. An opponent within one square has a held weapon sent flying two squares away from you in any direction you choose. Picking it back up requires a [[* Swapping Held Items][weapon swap]] minor action.

At the fifth level, assassins gain the *back stab* minor action. When an ally is withing 1 square of the enemy you are targeting with a melee attack and that enemy has no allies within 1 square, ignore any [[* Defense][defense]] provided by armor.

At the seventh level, assassins gain the *flourish strike* class feature. This lets you take an extra minor action whenever you perform a critical weapon attack. This feature can only be used once per turn. The minor action must be different than your other minor action.

At the ninth level, assassins gain the *traveling combatant* class feature. Whenever you are the target of an attack or spell, you make move 1 square after the attack or spell resolves.

At the eleventh level, assassins gain the *rapid strike* class feature. If you kill an opponent with a weapon strike, you may take an extra major action. This feature can only be used once per turn.

At the thirteenth level, assassins gain the *weapon catch* class feature. This lets you keep the weapon thrown with disarm instead of sending it flying.

At the fifteenth level, assassins gain the *criticaler* class feature. When making a weapon attack, roll two crit dice. If both dice manage to crit, the multipliers are combined.

At the sixteenth level, assassins gain the *criticalest* class feature. Critical strikes do 3x the damage instead of 2x.

** Scholar

Scholars are those who seek to understand the titan's influence on the world. The knowledge is only a mimicry, but even a fraction of that power is enough to demand respect.

Starting [[* Health Points (HP)][HP]]: 10

Starting [[* Magic Power (MP)][MP]]: 15

One magic system, including the [[* Ancient Whisperer][ancient whisperer]] magic system.

At the first level, scholars gain the *rest enjoyer* class feature. This allows the scholar use one respite dice without counting towards the level limit every [[* Respite][respite]].

At the third level, scholars gain the *spell insight* minor action. This lets you identify any spells that an enemy has prepared.

At the fifth level, scholars gain the *mage drain* major action. Declare an enemy. Until the beginning of your next turn, regain the [[* Magic Power (MP)][MP]] value of any spells that cast.

At the seventh level, scholars gain the *spell imprint* minor action. If you cast a spell last turn, it can be cast again as a minor action, but you cannot use the [[* Spell Cast][spell cast]] major action this turn.

At the ninth level, scholars gain the *arcane wisdom* class feature. This lets you discover the effects of an artifact as a [[* Town Actions][town action]].

At the eleventh level, scholars gain the *MP recycle* class feature. Gain d4 [[* Magic Power (MP)][MP]] at the end of every turn that you do not cast a spell.

At the thirteenth level, scholars gain the *spell disable* major action. Declare a spell that was learned from spell insight. The enemy who knew that spell is unable to cast it for the rest of the day. Only one spell per enemy can be affected by spell disable at a time.

At the fifteenth level, scholars gain the *magic osmosis* class feature. This lets you select another target to gain the [[* Magic Power (MP)][MP]] gathered from the recycle class feature.

At the sixteenth level, scholars gain the *spell chain* class feature. This turns the [[* Spell Cast][spell cast]] action into a minor action, and this action can be used as a minor action and major action in the same turn.

** Bereft

The Bereft are those without any advantage in life. Unlikely adventurers, but it is not for fate to say who are the greats.

HP per Level: 8
MP per Level: 3

No magic systems. No class features. Mad respect.

* Systems of Magic

The power of the titans left its mark on the world. The study of these marks led to the beginning of the practice of magic. Independently, the studies led in different paths that lead to the groups of magic that are currently known.

Each group requires a lifetime of practice and a focus to the craft. Even then, some advanced magics are only able to be learned by those who give their complete energy to the study. These are known as advanced magics, while the easier magics are called the standard magics.

** Ancient Whisperer

The ancient whisperer magic system can only be learned by the [[* Scholar][scholar]] class.

The Ancient Whisperers have studied the lost spoken language of the titans. Through great mental exertion, they can recall incantations the forgotten language, shaping the world as the titans once did.

The number of known incantations are shown in the following table.

#+begin_xtable
| Level | # Incantations Known |
|-------+----------------------|
|     1 |                    1 |
|     2 |                    2 |
|     3 |                    3 |
|     4 |                    4 |
|     5 |                    5 |
|     6 |                    6 |
|     7 |                    7 |
|     8 |                    8 |
|     9 |                    9 |
|    10 |                   10 |
|    11 |                   11 |
|    12 |                   12 |
|    13 |                   13 |
|    14 |                   14 |
|    15 |                   15 |
|    16 |                   16 |
#+end_xtable

** Elementalist

Elementalists draw from the latent magic left behind from the construction of the world.

Elemental spells, called sourceries, can be devastatingly powerful, but rely on the setup and maintenance of elemental catalysts. Elementalists learn major and minor sourceries that can be used as major and minor actions.

Elementalists work with the catalysts of heat, cold, earth, lightning, and dark.  Sourceries that create these catalysts are marked with a type and amount, e.g. creates heat 2. Spells that consume the catalysts are marked with type and cost, e.g. consumes heat 1. At the end of the elementalist's turn, the value of each catalyst type is reduced by 1 to a minimum of 0.

#+begin_xtable
| Level | # Major Sourceries Known | # Minor Sourceries Known |
|-------+--------------------------+--------------------------|
|     1 |                        1 |                        1 |
|     2 |                        2 |                        2 |
|     3 |                        2 |                        2 |
|     4 |                        3 |                        2 |
|     5 |                        3 |                        2 |
|     6 |                        4 |                        3 |
|     7 |                        4 |                        3 |
|     8 |                        5 |                        3 |
|     9 |                        5 |                        3 |
|    10 |                        6 |                        3 |
|    11 |                        6 |                        4 |
|    12 |                        7 |                        4 |
|    13 |                        7 |                        4 |
|    14 |                        8 |                        4 |
|    15 |                        8 |                        4 |
|    16 |                       10 |                        5 |
#+end_xtable

** Harvester

Harvesters utilize the remains of the fallen, twisting them to their own purposes. They collect soul pieces from those that die during combat, which are manipulated to their end through the use of spells called extractions.

The number of known extractions and maximum number of should pieces that can be held at the same time are shown in the following table.

#+begin_xtable
| Level | # Extractions Known | Max Soul Pieces |
|-------+---------------------+-----------------|
|     1 |                   1 |               3 |
|     2 |                   2 |               4 |
|     3 |                   2 |               4 |
|     4 |                   3 |               5 |
|     5 |                   3 |               5 |
|     6 |                   4 |               6 |
|     7 |                   4 |               6 |
|     8 |                   5 |               7 |
|     9 |                   5 |               7 |
|    10 |                   6 |               8 |
|    11 |                   6 |               8 |
|    12 |                   7 |               9 |
|    13 |                   7 |               9 |
|    14 |                   8 |              10 |
|    15 |                   8 |              10 |
|    16 |                  10 |              12 |
#+end_xtable

** Runecast

The Runecast are warriors that pursue the study of an ancient written language. By etching these runic symbols into their weapons and armor, they are able to bind the power of magic to physical objects, and augment their combat ability.

Runes carved into your weapons and armor can be activated with a minor action. Whenever the effect of the rune is used [[* Magic Power (MP)][MP]] is lost. The passive effects of these runes are always present once activated. Runecast are only able to modify their own equipment and can not add runes to [[* Artifacts][artifacts]].

The number of runes that can be equipped at a time is shown in the following table.

#+begin_xtable
| Level | Max # of Runes |
|-------+----------------|
|     1 |              1 |
|     2 |              1 |
|     3 |              1 |
|     4 |              2 |
|     5 |              2 |
|     6 |              2 |
|     7 |              3 |
|     8 |              3 |
|     9 |              3 |
|    10 |              4 |
|    11 |              4 |
|    12 |              4 |
|    13 |              5 |
|    14 |              5 |
|    15 |              5 |
|    16 |              6 |
#+end_xtable

** Spirit Caller

Spirit Callers hold a spiritual bond with their ancestors. In death, the spirits of the departed are able to impart their favors upon the physical world.

These effects are limited by the number of favors available and can be activated a number of times since the last [[* Full Recovery][full recovery]] as shown in the following table.

When used in combat, a spirit callers spells last until the end of combat. When used outside of combat, they last for [[* Presence][presence]]/4 hours or until the end of the next combat, whichever comes first.

#+begin_xtable
| Level | # Casts Per Recovery | # Favors Available |
|-------+----------------------+--------------------|
|     1 |                    2 |                  1 |
|     2 |                    4 |                  2 |
|     3 |                    4 |                  2 |
|     4 |                    4 |                  3 |
|     5 |                    4 |                  3 |
|     6 |                    6 |                  4 |
|     7 |                    6 |                  4 |
|     8 |                    6 |                  5 |
|     9 |                    6 |                  5 |
|    10 |                    6 |                  6 |
|    11 |                    8 |                  6 |
|    12 |                    8 |                  7 |
|    13 |                    8 |                  7 |
|    14 |                    8 |                  8 |
|    15 |                    8 |                  8 |
|    16 |                   10 |                 10 |
#+end_xtable

* Equipment

** Currency

The currency in the game are shells and pearls.

#+begin_xtable
| Currency     | Value (in Shells) |
|--------------+-------------------|
| Shells       |                 1 |
| Pearls       |               100 |
| Black Pearls |              1000 |
#+end_xtable

** Combat Equipment

Combat equipment includes weapons, armor, and shields.

Armor is considered worn equipment. Weapons and shields are considered held equipment.

Armor provides you with you base [[* Defense][defense]] and [[* Defense Threshold][defense threshold]] stats.

Only one set of armor can be worn at a time. Two one-handed combat items or one two-handed combat items can be worn at a time.

Characters can carry with them one set of armor and four hands worth of held items.

Switching held equipment, can done with the [[* Swapping Held Items][swapping held items]] minor action.

** Adventuring Equipment

In addition to combat equipment, it is wise to stock up on adventuring equipment. These include ropes, light sources, bags, etc.

There is no hard limit on carrying adventuring equipment, but the items you take with you must reasonably fit in a backpack or on a pack mule.

** Potions

Potions can be bought at an [[* Apothecary][apothecary]].

Potions provide such important utilities like healing and staving off negative effects, if you care about that sort of thing.

Up to 10 potions can be carried at a time.

** Artifacts

Artifacts are special items infused with great power. Artifacts can be of any item type, but are always better than base items. Artifacts may have requirements beyond the base item.

Artifacts are described by their rarit: rare, epic, or legendary.

Artifacts are valuable and coveted, so to have any is to paint a target on your back. Guard them carefully.

-----

#+begin_cw
Game on
#+end_cw
