#+Title: Titan Mage Lore
#+HTML_LINK_HOME: dummy value
#+DESCRIPTION: Learn about the world and creatures that inhabit the world of TitanMage TTRPG.
#+OPTIONS: toc:nil

* Foes

** Goblins & Spiders

Goblins are fiendish humanoid creatures that live by ambushing prey in the dark.

They are blue, hairless, and grow only to a meter high. They have four large black eyes that see very well in darkness and reflect light similar to those of a spider. They have a simple toothless mouth and slots for a nose.

On the topic of spiders, they have formed a symbiotic relationship with giant spiders. They act as a hunting party for the spiders bringing food back to the nest, while the spiders use web and venom on the victims to preserve the food and make it easier to eat.

Goblins are able to talk to each other with chitters, but no one has been able to decipher the language.

The spiders that inhabit their holes are also able to grow to a meter in size, as they have a more reliable food source. They have adapted to incapacitate larger prey with a stronger venom.

** Powder Ram

A powder ram is a common familiar of witches. The particulary fiesty rams are chosen by the witch and augmented with explosive runes. Their glowing red head and black horns warn off the wary.

** Undead

Through certain kinds of magic, the dead can be forced to walk again. When practiced by lesser spellcasters, the dead retain none of their mental ability or physical abilities.  They are husks of life that desire only to harm the living.

When practiced by master spellcasters, the undead maintain basic forms of speech and desire, but are still angry vengeful beings.

Because of the aggressive effect that this kind of magic has, it is often frowned upon.

A perfect reincarnation has not been achieved, but that doesn't stop people from trying.

-----

#+begin_cw
Game on
#+end_cw
